In [32]:
import pandas as pd
import numpy as np
movie = pd.read_csv("Datapython\movie.csv")
movie.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [34]:
df=movie
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [31]:
df.loc[df['color']=='160']='black'
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
1,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
2,Color,Sam Mendes,602,148,0,161,Rory Kinnear,11000,2.00074e+08,Action|Adventure|Thriller,...,994,English,UK,PG-13,2.45e+08,2015,393,6.8,2.35,85000
3,Color,Christopher Nolan,813,164,22000,23000,Christian Bale,27000,4.48131e+08,Action|Thriller,...,2701,English,USA,PG-13,2.5e+08,2012,23000,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131,NaN,Rob Walker,131,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12,7.1,NaN,0
5,Color,Andrew Stanton,462,132,475,530,Samantha Morton,640,7.30587e+07,Action|Adventure|Sci-Fi,...,738,English,USA,PG-13,2.637e+08,2012,632,6.6,2.35,24000
6,Color,Sam Raimi,392,156,0,4000,James Franco,24000,3.3653e+08,Action|Adventure|Romance,...,1902,English,USA,PG-13,2.58e+08,2007,11000,6.2,2.35,0
7,Color,Nathan Greno,324,100,15,284,Donna Murphy,799,2.00807e+08,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387,English,USA,PG,2.6e+08,2010,553,7.8,1.85,29000
8,Color,Joss Whedon,635,141,0,19000,Robert Downey Jr.,26000,4.58992e+08,Action|Adventure|Sci-Fi,...,1117,English,USA,PG-13,2.5e+08,2015,21000,7.5,2.35,118000
9,Color,David Yates,375,153,282,10000,Daniel Radcliffe,25000,3.01957e+08,Adventure|Family|Fantasy|Mystery,...,973,English,UK,PG,2.5e+08,2009,11000,7.5,2.35,10000
10,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
11,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
12,Color,Marc Forster,403,106,395,393,Mathieu Amalric,451,1.68368e+08,Action|Adventure,...,1243,English,UK,PG-13,2e+08,2008,412,6.7,2.35,0
13,Color,Gore Verbinski,313,151,563,1000,Orlando Bloom,40000,4.23033e+08,Action|Adventure|Fantasy,...,1832,English,USA,PG-13,2.25e+08,2006,5000,7.3,2.35,5000
14,Color,Gore Verbinski,450,150,563,1000,Ruth Wilson,40000,8.92899e+07,Action|Adventure|Western,...,711,English,USA,PG-13,2.15e+08,2013,2000,6.5,2.35,48000
15,Color,Zack Snyder,733,143,0,748,Christopher Meloni,15000,2.91022e+08,Action|Adventure|Fantasy|Sci-Fi,...,2536,English,USA,PG-13,2.25e+08,2013,3000,7.2,2.35,118000
16,Color,Andrew Adamson,258,150,80,201,Pierfrancesco Favino,22000,1.41614e+08,Action|Adventure|Family|Fantasy,...,438,English,USA,PG,2.25e+08,2008,216,6.6,2.35,0
17,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
18,Color,Rob Marshall,448,136,252,1000,Sam Claflin,40000,2.41064e+08,Action|Adventure|Fantasy,...,484,English,USA,PG-13,2.5e+08,2011,11000,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451,106,188,718,Michael Stuhlbarg,10000,1.79021e+08,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341,English,USA,PG-13,2.25e+08,2012,816,6.8,1.85,40000
20,Color,Peter Jackson,422,164,0,773,Adam Brown,5000,2.55108e+08,Adventure|Fantasy,...,802,English,New Zealand,PG-13,2.5e+08,2014,972,7.5,2.35,65000
21,Color,Marc Webb,599,153,464,963,Andrew Garfield,15000,2.62031e+08,Action|Adventure|Fantasy,...,1225,English,USA,PG-13,2.3e+08,2012,10000,7,2.35,56000
22,Color,Ridley Scott,343,156,0,738,William Hurt,891,1.0522e+08,Action|Adventure|Drama|History,...,546,English,USA,PG-13,2e+08,2010,882,6.7,2.35,17000
23,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
24,Color,Chris Weitz,251,113,129,1000,Eva Green,16000,7.00835e+07,Adventure|Family|Fantasy,...,666,English,USA,PG-13,1.8e+08,2007,6000,6.1,2.35,0
25,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
26,black,black,black,black,black,black,black,black,black,black,...,black,black,black,black,black,black,black,black,black,black
27,Color,Anthony Russo,516,147,94,11000,Scarlett Johansson,21000,4.07197e+08,Action|Adventure|Sci-Fi,...,1022,English,USA,PG-13,2.5e+08,2016,19000,8.2,2.35,72000
28,Color,Peter Berg,377,131,532,627,Alexander Skarsgård,14000,6.51732e+07,Action|Adventure|Sci-Fi|Thriller,...,751,English,USA,PG-13,2.09e+08,2012,10000,5.9,2.35,44000
29,Color,Colin Trevorrow,644,124,365,1000,Judy Greer,3000,6.52177e+08,Action|Adventure|Sci-Fi|Thriller,...,1290,English,USA,PG-13,1.5e+08,2015,2000,7,2,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,Color,Eric Eason,28,79,3,42,Panchito Gómez,93,NaN,Drama|Family,...,21,English,USA,NaN,24000,2002,46,7,1.78,61
4887,Color,Uwe Boll,58,80,892,492,Katharine Isabelle,986,NaN,Action|Crime|Thriller,...,129,English,Canada,R,NaN,2009,918,6.3,2.35,0
4888,Black and White,Richard Linklater,61,100,0,0,Richard Linklater,5,1.22751e+06,Comedy|Drama,...,80,English,USA,R,23000,1991,0,7.1,1.37,2000
4889,Color,Joseph Mazzella,NaN,90,0,9,Mikaal Bates,313,NaN,Crime|Drama|Thriller,...,2,English,USA,NaN,25000,2015,25,4.8,NaN,33
4890,Color,Travis Legge,1,90,138,138,Suzi Lorraine,370,NaN,Comedy|Romance,...,3,English,USA,NaN,22000,2013,184,3.3,1.78,200
4891,Color,Alex Kendrick,5,120,589,4,Lisa Arnold,51,NaN,Drama,...,49,English,USA,NaN,20000,2003,49,6.9,1.85,725
4892,Color,Marcus Nispel,43,91,158,265,Brittany Curran,630,NaN,Horror|Mystery|Thriller,...,33,English,USA,R,NaN,2015,512,4.6,1.85,0
4893,NaN,Brandon Landers,NaN,143,8,8,Alana Kaniewski,720,NaN,Drama|Horror|Thriller,...,8,English,USA,NaN,17350,2011,19,3,NaN,33
4894,Color,Jay Duplass,51,85,157,10,Katie Aselton,830,192467,Comedy|Drama|Romance,...,71,English,USA,R,15000,2005,224,6.6,NaN,297
4895,Black and White,Jim Chuchu,6,60,0,4,Olwenya Maina,147,NaN,Drama,...,1,Swahili,Kenya,NaN,15000,2014,19,7.4,NaN,45
4896,Color,Daryl Wein,22,88,38,211,Heather Burns,331,76382,Romance,...,8,English,USA,NaN,15000,2009,212,6.2,2.35,324
4897,Color,Jason Trost,42,78,91,86,Jason Trost,407,NaN,Sci-Fi|Thriller,...,35,English,USA,Unrated,20000,2011,91,4,2.35,835
4898,Color,John Waters,73,108,0,105,Mink Stole,462,180483,Comedy|Crime|Horror,...,183,English,USA,NC-17,10000,1972,143,6.1,1.37,0
4899,Color,Olivier Assayas,81,110,107,45,Béatrice Dalle,576,136007,Drama|Music|Romance,...,39,French,France,R,4500,2004,133,6.9,2.35,171
4900,Color,Jafar Panahi,64,90,397,0,Nargess Mamizadeh,5,673780,Drama,...,26,Persian,Iran,Not Rated,10000,2000,0,7.5,1.85,697
4901,Black and White,Ivan Kavanagh,12,83,18,0,Michael Parle,10,NaN,Horror,...,1,English,Ireland,NaN,10000,2007,5,6.7,1.33,105
4902,Color,Kiyoshi Kurosawa,78,111,62,6,Anna Nakagawa,89,94596,Crime|Horror|Mystery|Thriller,...,50,Japanese,Japan,NaN,1e+06,1997,13,7.4,1.85,817
4903,Color,Tadeo Garcia,NaN,84,5,12,Michael Cortez,21,NaN,Drama,...,3,English,USA,NaN,NaN,2004,20,6.1,NaN,22
4904,Color,Thomas L. Phillips,13,82,120,84,Joe Coffey,785,NaN,Comedy|Horror|Thriller,...,8,English,USA,NaN,200000,2012,98,5.4,16,424
4905,Color,Ash Baron-Cohen,10,98,3,152,Stanley B. Herman,789,NaN,Crime|Drama,...,14,English,USA,NaN,NaN,1995,194,6.4,NaN,20
4906,Color,Shane Carruth,143,77,291,8,David Sullivan,291,424760,Drama|Sci-Fi|Thriller,...,371,English,USA,PG-13,7000,2004,45,7,1.85,19000
4907,Color,Neill Dela Llana,35,80,0,0,Edgar Tancangco,0,70071,Thriller,...,35,English,Philippines,Not Rated,7000,2005,0,6.3,NaN,74
4908,Color,Robert Rodriguez,56,81,0,6,Peter Marquardt,121,2.04092e+06,Action|Crime|Drama|Romance|Thriller,...,130,Spanish,USA,R,7000,1992,20,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84,2,2,John Considine,45,NaN,Crime|Drama,...,1,English,USA,PG-13,3250,2005,44,7.8,NaN,4
4910,Color,Edward Burns,14,95,0,133,Caitlin FitzGerald,296,4584,Comedy|Drama,...,14,English,USA,Not Rated,9000,2011,205,6.4,NaN,413
4911,Color,Scott Smith,1,87,2,318,Daphne Zuniga,637,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013,470,7.7,NaN,84
4912,Color,NaN,43,43,NaN,319,Valorie Curry,841,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593,7.5,16,32000
4913,Color,Benjamin Roberds,13,76,0,0,Maxwell Moody,0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400,2013,0,6.3,NaN,16
4914,Color,Daniel Hsia,14,100,0,489,Daniel Henney,946,10443,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012,719,6.3,2.35,660
4915,Color,Jon Gunn,43,90,16,16,Brian Herzlinger,86,85222,Documentary,...,84,English,USA,PG,1100,2004,23,6.6,1.85,456

In [2]:
df=movie

In [3]:
df.isnull().sum()

color                         19
director_name                102
num_critic_for_reviews        49
duration                      15
director_facebook_likes      102
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        862
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                152
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               300
budget                       484
title_year                   106
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 326
movie_facebook_likes           0
dtype: int64

In [4]:
movie.tail(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [10]:
movie[['color','duration']]

                color  duration
0               Color     178.0
1               Color     169.0
2               Color     148.0
3               Color     164.0
4                 NaN       NaN
5               Color     132.0
6               Color     156.0
7               Color     100.0
8               Color     141.0
9               Color     153.0
10              Color     183.0
11              Color     169.0
12              Color     106.0
13              Color     151.0
14              Color     150.0
15              Color     143.0
16              Color     150.0
17              Color     173.0
18              Color     136.0
19              Color     106.0
20              Color     164.0
21              Color     153.0
22              Color     156.0
23              Color     186.0
24              Color     113.0
25              Color     201.0
26              Color     194.0
27              Color     147.0
28              Color     131.0
29              Color     124.0
...               ...       ...
4886            Color      79.0
4887            Color      80.0
4888  Black and White     100.0
4889            Color      90.0
4890            Color      90.0
4891            Color     120.0
4892            Color      91.0
4893              NaN     143.0
4894            Color      85.0
4895  Black and White      60.0
4896            Color      88.0
4897            Color      78.0
4898            Color     108.0
4899            Color     110.0
4900            Color      90.0
4901  Black and White      83.0
4902            Color     111.0
4903            Color      84.0
4904            Color      82.0
4905            Color      98.0
4906            Color      77.0
4907            Color      80.0
4908            Color      81.0
4909            Color      84.0
4910            Color      95.0
4911            Color      87.0
4912            Color      43.0
4913            Color      76.0
4914            Color     100.0
4915            Color      90.0

[4916 rows x 2 columns]

In [18]:
movie.iloc[0:4,1:3]

       director_name  num_critic_for_reviews
0      James Cameron                   723.0
1     Gore Verbinski                   302.0
2         Sam Mendes                   602.0
3  Christopher Nolan                   813.0

In [21]:
for index, row in movie.iterrows():
    print(index,row['director_name'])

0 James Cameron
1 Gore Verbinski
2 Sam Mendes
3 Christopher Nolan
4 Doug Walker
5 Andrew Stanton
6 Sam Raimi
7 Nathan Greno
8 Joss Whedon
9 David Yates
10 Zack Snyder
11 Bryan Singer
12 Marc Forster
13 Gore Verbinski
14 Gore Verbinski
15 Zack Snyder
16 Andrew Adamson
17 Joss Whedon
18 Rob Marshall
19 Barry Sonnenfeld
20 Peter Jackson
21 Marc Webb
22 Ridley Scott
23 Peter Jackson
24 Chris Weitz
25 Peter Jackson
26 James Cameron
27 Anthony Russo
28 Peter Berg
29 Colin Trevorrow
30 Sam Mendes
31 Sam Raimi
32 Shane Black
33 Tim Burton
34 Brett Ratner
35 Dan Scanlon
36 Michael Bay
37 Michael Bay
38 Sam Raimi
39 Marc Webb
40 Joseph Kosinski
41 John Lasseter
42 Martin Campbell
43 Lee Unkrich
44 McG
45 James Wan
46 Marc Forster
47 Bryan Singer
48 J.J. Abrams
49 Bryan Singer
50 Baz Luhrmann
51 Mike Newell
52 Guillermo del Toro
53 Michael Bay
54 Steven Spielberg
55 Peter Sohn
56 Mark Andrews
57 Justin Lin
58 Andrew Stanton
59 Brett Ratner
60 Roland Emmerich
61 Robert Zemeckis
62 Lana Wachowski
63 David Yates
64 Andrew Adamson
65 Bryan Singer
66 Christopher Nolan
67 Pete Docter
68 Rob Letterman
69 Jon Favreau
70 Martin Scorsese
71 Barry Sonnenfeld
72 Rob Cohen
73 David Ayer
74 Tom Shadyac
75 Doug Liman
76 Kevin Reynolds
77 Stephen Sommers
78 Pete Docter
79 Jon Favreau
80 Jon Favreau
81 Rupert Sanders
82 Robert Stromberg
83 Matt Reeves
84 Roland Joffé
85 Carl Rinsch
86 Anthony Russo
87 Mike Mitchell
88 Brad Bird
89 Don Hall
90 Rich Moore
91 Robert Zemeckis
92 Roland Emmerich
93 Dean DeBlois
94 Jonathan Mostow
95 James Gunn
96 Christopher Nolan
97 Christopher Nolan
98 Hideaki Anno
99 Peter Jackson
100 Rob Cohen
101 David Fincher
102 Matthew Vaughn
103 Francis Lawrence
104 Jon Turteltaub
105 Wolfgang Petersen
106 James Bobin
107 Chris Miller
108 Duncan Jones
109 Alan Taylor
110 Michael Apted
111 Michael Bay
112 Michael Bay
113 Oliver Stone
114 David Yates
115 Mike Newell
116 Peter Berg
117 Francis Lawrence
118 Tim Burton
119 Brad Bird
120 Christopher Nolan
121 Eric Darnell
122 Shawn Levy
123 Gavin Hood
124 Lana Wachowski
125 Chris Buck
126 Lana Wachowski
127 Alan Taylor
128 George Miller
129 Ron Howard
130 Kenneth Branagh
131 Byron Howard
132 Hoyt Yeatman
133 Jonathan Liebesman
134 Tim Burton
135 Christopher McQuarrie
136 Joe Johnston
137 Steve Hickner
138 Jennifer Yuh Nelson
139 M. Night Shyamalan
140 J.J. Abrams
141 Roland Emmerich
142 Simon Wells
143 David Bowers
144 Joe Wright
145 Rob Minkoff
146 Wolfgang Petersen
147 Eric Darnell
148 Lee Tamahori
149 Paul Feig
150 Michael Bay
151 Barry Sonnenfeld
152 Robert Zemeckis
153 Alessandro Carloni
154 Brad Bird
155 Peter Ramsey
156 Dean Parisot
157 Edward Zwick
158 Ridley Scott
159 J.J. Abrams
160 Sam Raimi
161 Dean DeBlois
162 Alex Proyas
163 Rob Cohen
164 Zack Snyder
165 Richard Donner
166 Ang Lee
167 Jon M. Chu
168 Breck Eisner
169 Hironobu Sakaguchi
170 Joe Johnston
171 Michael Apted
172 Peter Weir
173 Bill Condon
174 George Miller
175 Louis Leterrier
176 nan
177 Steven Spielberg
178 Alejandro G. Iñárritu
179 David Soren
180 Gore Verbinski
181 Eric Darnell
182 Paul Greengrass
183 Mark Osborne
184 Peyton Reed
185 Francis Lawrence
186 Tim Johnson
187 Steven Spielberg
188 Michael Bay
189 Chris Miller
190 Phillip Noyce
191 Darren Aronofsky
192 Steven Spielberg
193 Alfonso Cuarón
194 Baz Luhrmann
195 M. Night Shyamalan
196 Eric Leighton
197 Matt Birch
198 Shawn Levy
199 Tom McGrath
200 Chris Columbus
201 Robert Schwentke
202 Gore Verbinski
203 Matt Birch
204 Francis Lawrence
205 Ron Howard
206 Carlos Saldanha
207 Bryan Singer
208 Justin Lin
209 Guy Ritchie
210 Louis Leterrier
211 Paul Verhoeven
212 John McTiernan
213 Tony Gilroy
214 Joel Schumacher
215 Ron Howard
216 Roland Emmerich
217 John Woo
218 Wolfgang Petersen
219 Tim Story
220 Ang Lee
221 Mark Steven Johnson
222 Paul Greengrass
223 McG
224 Ridley Scott
225 Rob Minkoff
226 Neill Blomkamp
227 David Twohy
228 José Padilha
229 Lana Wachowski
230 James L. Brooks
231 James Mangold
232 Joseph Kosinski
233 George Lucas
234 George Lucas
235 Pete Docter
236 James Mangold
237 George Lucas
238 Kirk De Micco
239 Frédéric Forestier
240 John Woo
241 Cedric Nicolas-Troyan
242 Jonathan Liebesman
243 Alfonso Cuarón
244 Roger Donaldson
245 Dave Green
246 Josh Trank
247 Shawn Levy
248 Brad Peyton
249 Roger Spottiswoode
250 Roland Emmerich
251 Steven Soderbergh
252 Doug Liman
253 Robert Schwentke
254 Martin Scorsese
255 Rob Letterman
256 Michel Gondry
257 nan
258 Noam Murro
259 Raja Gosnell
260 Will Finn
261 Robert Schwentke
262 Shawn Levy
263 Raja Gosnell
264 Jan de Bont
265 Gavin Hood
266 Len Wiseman
267 Peter Jackson
268 Frank Coraci
269 Michael Mann
270 Bo Welch
271 Alex Proyas
272 Ridley Scott
273 Rob Minkoff
274 Ron Clements
275 Ridley Scott
276 Christopher Barnard
277 Michael Bay
278 Peter Chelsom
279 Dominic Sena
280 Ridley Scott
281 Steven Spielberg
282 Chris Columbus
283 Martin Campbell
284 Tim Burton
285 James Cameron
286 Michael Mann
287 Ridley Scott
288 James Cameron
289 Tony Scott
290 Paul Weitz
291 Adam McKay
292 Chuck Russell
293 Quentin Tarantino
294 Gary Trousdale
295 Mark Dindal
296 Simon West
297 Jon Turteltaub
298 Stefen Fangmeier
299 Spike Jonze
300 Chris Wedge
301 Florian Henckel von Donnersmarck
302 Peter Hyams
303 Edward Zwick
304 Martin Scorsese
305 Joel Schumacher
306 Paul Verhoeven
307 Tom Tykwer
308 Zack Snyder
309 Pitof
310 Brett Ratner
311 Ron Clements
312 Brad Silberling
313 Patrick Hughes
314 Ericson Core
315 Lawrence Guterman
316 Ron Howard
317 Ron Underwood
318 Paul Greengrass
319 Steve Martino
320 David Mamet
321 Stephen Sommers
322 Martin Scorsese
323 Yimou Zhang
324 Ash Brannon
325 Frank Oz
326 Ridley Scott
327 Jay Roach
328 Luc Besson
329 Michael Patrick King
330 Bibo Bergeron
331 Steve Martino
332 Kenneth Branagh
333 Peter Jackson
334 Andrew Stanton
335 Peter Jackson
336 Peter Jackson
337 Sergey Bodrov
338 Simon West
339 Wally Pfister
340 Joe Johnston
341 Rupert Wyatt
342 Mark Waters
343 John Moore
344 John Lee Hancock
345 Brad Bird
346 Renny Harlin
347 Chris Columbus
348 Barry Sonnenfeld
349 John Lasseter
350 Tony Scott
351 Brett Ratner
352 Robert Zemeckis
353 Phil Lord
354 Carlos Saldanha
355 Ben Stiller
356 McG
357 Martin Scorsese
358 Tony Bancroft
359 Ben Stiller
360 David Fincher
361 John McTiernan
362 Guy Ritchie
363 Timur Bekmambetov
364 Gary Trousdale
365 Walt Becker
366 Bryan Singer
367 Dennis Dugan
368 Chris Columbus
369 Steven Spielberg
370 Rob Minkoff
371 Robert Zemeckis
372 Paul Verhoeven
373 Sydney Pollack
374 Thor Freudenthal
375 Jan de Bont
376 Jon M. Chu
377 Phillip Noyce
378 Tony Scott
379 Brian De Palma
380 Carlos Saldanha
381 Chris Columbus
382 Mick Jackson
383 Alan J. Pakula
384 Kathryn Bigelow
385 John Milius
386 Ron Howard
387 Andrey Konchalovskiy
388 Gary Ross
389 Jan de Bont
390 Robert Zemeckis
391 George Miller
392 Paul Greengrass
393 Wolfgang Petersen
394 Steven Soderbergh
395 Paul W.S. Anderson
396 Genndy Tartakovsky
397 Kevin Lima
398 nan
399 Daniel Espinosa
400 Kevin Lima
401 Brett Ratner
402 Nancy Meyers
403 Tony Scott
404 Nancy Meyers
405 Steven Soderbergh
406 Roger Allers
407 Neil Burger
408 Jean-Jacques Annaud
409 Peter Berg
410 John McTiernan
411 Rob Marshall
412 Justin Lin
413 Sarah Smith
414 Martin Brest
415 Andrew Davis
416 Bob Fosse
417 Tarsem Singh
418 Edgar Wright
419 Jon Amiel
420 Peter Segal
421 Raja Gosnell
422 Pete Travis
423 Frank Coraci
424 George A. Romero
425 Brad Peyton
426 Doug Liman
427 Guillermo del Toro
428 David Fincher
429 Roger Spottiswoode
430 Tom Shadyac
431 Sylvester Stallone
432 Brian De Palma
433 Gary Ross
434 Todd Phillips
435 Tim Burton
436 Tim Johnson
437 Dean DeBlois
438 Gary Winick
439 Mimi Leder
440 Dean Parisot
441 Peter Segal
442 Mike Mitchell
443 Dennis Dugan
444 Peter Segal
445 Nancy Meyers
446 Martin Scorsese
447 Seth Gordon
448 Chris Wedge
449 John Woo
450 Adam Shankman
451 Sam Mendes
452 Dennis Dugan
453 nan
454 Simon West
455 D.J. Caruso
456 Anthony Minghella
457 Albert Hughes
458 Les Mayfield
459 Jan de Bont
460 Joe Pytka
461 Shawn Levy
462 Scott Derrickson
463 Richard Donner
464 David Ayer
465 Ivan Reitman
466 Eric Brevig
467 Kelly Asbury
468 Frank Coraci
469 Stephen Hopkins
470 Jonathan Demme
471 Henry Jaglom
472 Genndy Tartakovsky
473 nan
474 James Algar
475 Simon Wells
476 Ron Underwood
477 Dominic Sena
478 Martin Campbell
479 Vincent Ward
480 Steven Brill
481 Terry Gilliam
482 Tim Burton
483 Lucile Hadzihalilovic
484 Lee Tamahori
485 Jonathan Mostow
486 Roger Donaldson
487 Rob Cohen
488 Barry Cook
489 Roger Christian
490 Joe Dante
491 Rob Marshall
492 Richard Donner
493 Kevin Costner
494 George Miller
495 Breck Eisner
496 Antony Hoffman
497 Luc Besson
498 Jacques Perrin
499 Peter Hyams
500 Paul W.S. Anderson
501 Andrés Couturier
502 Ron Howard
503 Roger Allers
504 Brad Peyton
505 Cody Cameron
506 Brett Ratner
507 Joe Johnston
508 Dennis Dugan
509 John Singleton
510 Mark Osborne
511 Oliver Hirschbiegel
512 Des McAnuff
513 Yarrow Cheney
514 Stephen Norrington
515 Pierre Coffin
516 Roland Emmerich
517 Steven Spielberg
518 Eric Darnell
519 Alfonso Cuarón
520 Bryan Singer
521 Timur Bekmambetov
522 Michael Bay
523 Carlos Saldanha
524 Peter Segal
525 Adam Shankman
526 Renny Harlin
527 David Kellogg
528 Louis Leterrier
529 Dennis Dugan
530 Steven Spielberg
531 nan
532 Thor Freudenthal
533 Martin Campbell
534 Mike Nichols
535 Bibo Bergeron
536 Bill Condon
537 nan
538 F. Gary Gray
539 Steven Spielberg
540 Antoine Fuqua
541 Robert Luketic
542 Guy Ritchie
543 James L. Brooks
544 Gil Kenan
545 Barry Levinson
546 Jerry Zucker
547 Andy Tennant
548 Tarsem Singh
549 Florent-Emilio Siri
550 Don Bluth
551 Ron Shelton
552 Paul W.S. Anderson
553 David Pastor
554 Henry Selick
555 John Moore
556 M. Night Shyamalan
557 Kyle Balda
558 Zack Snyder
559 Brian De Palma
560 Barry Levinson
561 Clay Kaytis
562 Andy Tennant
563 Judd Apatow
564 Peter Berg
565 Adam McKay
566 Steve Carr
567 Mel Gibson
568 Sam Mendes
569 David Silverman
570 Frank Darabont
571 Renny Harlin
572 Jean-Jacques Annaud
573 M. Night Shyamalan
574 Betty Thomas
575 M. Night Shyamalan
576 Andrew Adamson
577 John Lasseter
578 Garry Marshall
579 Rob Cohen
580 Paul Tibbitt
581 Ron Howard
582 Quentin Tarantino
583 Steven Spielberg
584 Renny Harlin
585 Clark Johnson
586 nan
587 Cameron Crowe
588 M. Night Shyamalan
589 Paul W.S. Anderson
590 Betty Thomas
591 Randall Wallace
592 Antoine Fuqua
593 Jonathan Frakes
594 Jonathan Liebesman
595 Tim Burton
596 Mike Nichols
597 Steven Spielberg
598 George Clooney
599 James Cameron
600 Oliver Stone
601 Gary Shore
602 Edward Zwick
603 Matthew Vaughn
604 Jean-Jacques Annaud
605 Ron Howard
606 Joel Schumacher
607 Andrzej Bartkowiak
608 Betty Thomas
609 Måns Mårlind
610 Adam Shankman
611 Gregory Hoblit
612 Gary McKendry
613 John McTiernan
614 Wych Kaosayananda
615 Mikael Salomon
616 Bobby Farrelly
617 Will Finn
618 Michael Mann
619 Kerry Conran
620 Michael Caton-Jones
621 Mikael Håfström
622 Renny Harlin
623 Phil Alden Robinson
624 David Slade
625 Frank Oz
626 Pierre Coffin
627 Joseph Ruben
628 Seth MacFarlane
629 Alejandro Amenábar
630 Kinka Usher
631 Bobby Farrelly
632 Michael Mann
633 Craig Gillespie

634 Ridley Scott
635 Jay Roach
636 Timur Bekmambetov
637 Jon Amiel
638 nan
639 Rob Bowman
640 Doug Lefler
641 Steven Spielberg
642 Scott Waugh
643 Nancy Meyers
644 Chris Wedge
645 Lawrence Kasdan
646 Steven Spielberg
647 Lana Wachowski
648 Ron Howard
649 Michael Lembeck
650 Tom Hooper
651 Nora Ephron
652 Adam McKay
653 Martin Campbell
654 Todd Phillips
655 Angelina Jolie Pitt
656 Clint Eastwood
657 Renny Harlin
658 John Woo
659 Jon Turteltaub
660 Oliver Stone
661 Mike Newell
662 Larry Charles
663 Stanley Kubrick
664 Will Gluck
665 Glenn Ficarra
666 McG
667 David S. Goyer
668 John Milius
669 Mike Nichols
670 Paul W.S. Anderson
671 Paul W.S. Anderson
672 Renny Harlin
673 Taylor Hackford
674 Jon Favreau
675 David Fincher
676 McG
677 nan
678 Michael Lehmann
679 Nora Ephron
680 Stuart Beattie
681 Roman Polanski
682 Rob Bowman
683 Frank Miller
684 Sydney Pollack
685 Baltasar Kormákur
686 Tom Tykwer
687 Jay Roach
688 David Bowers
689 Steven Spielberg
690 Lawrence Kasdan
691 Phillip Noyce
692 Daniel Lee
693 Keenen Ivory Wayans
694 Jonathan Mostow
695 Rob Reiner
696 Marco Schnabel
697 Demian Lichtenstein
698 Quentin Tarantino
699 Josh Gordon
700 Tim Hill
701 Zack Snyder
702 Jay Roach
703 David Frankel
704 Frank Darabont
705 Walt Becker
706 Mark Dindal
707 David Fincher
708 Doug Liman
709 Martin Campbell
710 Simon West
711 Peter Weir
712 Brenda Chapman
713 Steve Carr
714 Baltasar Kormákur
715 Lawrence Guterman
716 F. Gary Gray
717 Marc Lawrence
718 Eric Darnell
719 Peter Billingsley
720 Tony Scott
721 Adam Shankman
722 Wes Ball
723 Ryan Murphy
724 Brett Ratner
725 Robert Schwentke
726 Oliver Stone
727 Robert Redford
728 Michael Mann
729 Chuck Russell
730 Jay Russell
731 Christopher McQuarrie
732 Renny Harlin
733 Kenny Ortega
734 Steven Soderbergh
735 David McNally
736 Henry Selick
737 M. Night Shyamalan
738 Tony Scott
739 Brian Robbins
740 Todd Phillips
741 Brian Levant
742 Guillermo del Toro
743 Steven Zaillian
744 Chris Butler
745 Michael Caton-Jones
746 John Woo
747 Jon Avnet
748 Sam Fell
749 nan
750 Kevin Donovan
751 Geoff Murphy
752 Kenneth Branagh
753 David O. Russell
754 Babak Najafi
755 Jean-Pierre Jeunet
756 Antoine Fuqua
757 Graham Annable
758 Griffin Dunne
759 Phil Lord
760 John Pasquin
761 Rob Bowman
762 Ruben Fleischer
763 Harold Ramis
764 Clint Eastwood
765 Kevin Macdonald
766 Tony Gilroy
767 Donald Petrie
768 Clark Johnson
769 Jorge Blanco
770 Stuart Baird
771 Joel Coen
772 Robert Lorenz
773 Martin Campbell
774 Peter Hyams
775 Harold Ramis
776 Jon Avnet
777 Harold Becker
778 Joe Wright
779 Robert Redford
780 Cameron Crowe
781 Tim Hill
782 Lee Tamahori
783 Scott Stewart
784 Patrick Gilmore
785 Paul W.S. Anderson
786 Tom Shadyac
787 Brian De Palma
788 Tony Bill
789 Rod Lurie
790 Walter Hill
791 Akiva Goldsman
792 Harald Zwart
793 Brian Robbins
794 Walter Salles
795 Ron Howard
796 Iain Softley
797 Frank Miller
798 David Koepp
799 Uwe Boll
800 Martin Campbell
801 Pou-Soi Cheang
802 John Dahl
803 Tim Miller
804 Stephen Herek
805 Clint Eastwood
806 Rob Letterman
807 nan
808 Mark Waters
809 Brian Levant
810 Peter MacDonald
811 George Clooney
812 Frank Coraci
813 Marc Lawrence
814 Shawn Levy
815 Paul W.S. Anderson
816 Anthony Hemingway
817 nan
818 Taylor Hackford
819 Sean Anders
820 Rob Cohen
821 Brett Ratner
822 Mark Neveldine
823 John Madden
824 nan
825 Adam Shankman
826 Kevin Bray
827 Robert Zemeckis
828 Tim Hill
829 Jay Roach
830 Mike Gabriel
831 Richard Donner
832 Tom Shadyac
833 Andy Tennant
834 Sam Weisman
835 Jesse Dylan
836 Paul Greengrass
837 Shawn Levy
838 Brad Silberling
839 Antoine Fuqua
840 Wayne Wang
841 Tony Scott
842 Gabriele Muccino
843 Robert Schwentke
844 Barry Levinson
845 Brad Silberling
846 Quentin Tarantino
847 Frank Oz
848 nan
849 Quentin Tarantino
850 Andrey Konchalovskiy
851 Robert Zemeckis
852 Tom Dey
853 Stuart Baird
854 Mark Waters
855 Rob Minkoff
856 Jimmy Hayward
857 David Fincher
858 Alan Parker
859 John Frankenheimer
860 Stephen Hopkins
861 Paul King
862 Akiva Schaffer
863 William Friedkin
864 Jon Turteltaub
865 Bobby Farrelly
866 Kent Alterman
867 Peter Lord
868 Clint Eastwood
869 Andrew Davis
870 Tony Scott
871 Joel Schumacher
872 Shekhar Kapur
873 Karyn Kusama
874 Ron Maxwell
875 Robert Butler
876 Karey Kirkpatrick
877 James Bobin
878 Jonathan Frakes
879 Steve Antin
880 Jean-Pierre Jeunet
881 Stanley Kubrick
882 Jim Gillespie
883 Guillermo del Toro
884 Gabriele Muccino
885 Walter Hill
886 Francis Ford Coppola
887 Cameron Crowe
888 Anthony Russo
889 Richard Lester
890 Martin Brest
891 Steven Zaillian
892 John Singleton
893 Don Bluth
894 Baz Luhrmann
895 Harold Becker
896 Scott Cooper
897 Clint Eastwood
898 F. Gary Gray
899 Robert Rodriguez
900 Jonathan Demme
901 Curtis Hanson
902 Steven Spielberg
903 Kathryn Bigelow
904 Peyton Reed
905 Phyllida Lloyd
906 Garry Marshall
907 Jay Chandrasekhar
908 Terrence Malick
909 David Dobkin
910 Milos Forman
911 Martin Scorsese
912 Pierre Morel
913 Paul Hunter
914 Bobby Farrelly
915 Steve Oedekerk
916 John Whitesell
917 Chris Weitz
918 Andrew Adamson
919 George Nolfi
920 Kevin Reynolds
921 Cameron Crowe
922 Seth MacFarlane
923 James L. Brooks
924 Tom Shadyac
925 Adam McKay
926 Steven Brill
927 J.J. Abrams
928 Steven Soderbergh
929 Donald Petrie
930 Phil Lord
931 Neil Jordan
932 Peyton Reed
933 Rawson Marshall Thurber
934 Chris Columbus
935 Sean Anders
936 Rob Marshall
937 Spike Lee
938 Brian Helgeland
939 Frank Marshall
940 Cameron Crowe
941 Alex Proyas
942 Tom Dey
943 Hideo Nakata
944 Glenn Ficarra
945 Peter Hewitt
946 Joe Roth
947 Bennett Miller
948 Wolfgang Petersen
949 Jaume Collet-Serra
950 Andy Fickman
951 James McTeigue
952 David Dobkin
953 nan
954 Matthew O'Callaghan
955 Angela Robinson
956 Gary Fleder
957 Tommy Wirkola
958 Adrian Lyne
959 D.J. Caruso
960 Stephen Gaghan
961 Michael Bay
962 Jorge R. Gutiérrez
963 Richard Loncraine
964 Clint Eastwood
965 Ridley Scott
966 David Fincher
967 Christophe Gans
968 Howard Deutch
969 Jon Hurwitz
970 F. Gary Gray
971 Steven Quale
972 John Landis
973 Joe Dante
974 David Dobkin
975 Mimi Leder
976 Alexander Witt
977 Beeban Kidron
978 Carl Franklin
979 Steven Seagal
980 Robert Rodriguez
981 Danny Boyle
982 Garry Marshall
983 James McTeigue
984 Sam Raimi
985 nan
986 Andrew Bergman
987 Tom Dey
988 Clint Eastwood
989 Barbet Schroeder
990 Richard Donner
991 Peter Webber
992 Rob Reiner
993 Andrew Niccol
994 John McTiernan
995 Clint Eastwood
996 Tom Tykwer
997 John Carpenter
998 nan
999 Brad Bird
1000 Wes Anderson
1001 Gary Ross
1002 Alan Parker
1003 Stephen Herek
1004 Jaume Collet-Serra
1005 David Cronenberg
1006 John Stockwell
1007 Luc Besson
1008 David Gordon Green
1009 Jim Sheridan
1010 Costa-Gavras
1011 Patrick Read Johnson
1012 Roland Joffé
1013 Doug Liman
1014 nan
1015 Tony Scott
1016 William Friedkin
1017 Mark Neveldine
1018 Richard LaGravenese
1019 Danny DeVito
1020 Ben Stiller
1021 George Armitage
1022 Mike Nichols
1023 Patrick Lussier
1024 Andrzej Bartkowiak
1025 James Wong
1026 nan
1027 Renny Harlin
1028 Richard Curtis
1029 Steven Soderbergh
1030 Steven Spielberg
1031 Joe Wright
1032 Neill Blomkamp
1033 Phillip Noyce
1034 David Fincher
1035 Chuck Bowman
1036 David O. Russell
1037 Daniel Espinosa
1038 Jerry Zucker
1039 Iain Softley
1040 James Mangold
1041 Harold Ramis
1042 Francis Ford Coppola
1043 James Mangold
1044 Olivier Megaton
1045 Steven Soderbergh
1046 Ben Stiller
1047 Deepa Mehta
1048 Warren Beatty
1049 John McTiernan
1050 Penny Marshall
1051 Ted Kotcheff
1052 Andrei Tarkovsky
1053 Paul Bolger
1054 Stephen Frears
1055 P.J. Hogan
1056 Joe Roth
1057 Christopher Nolan
1058 Jonathan Frakes
1059 Jimmy Hayward
1060 Edward Zwick
1061 Tom Shadyac
1062 Brad Furman
1063 Terence Young
1064 Brian Levant
1065 Olivier Megaton
1066 David Zucker
1067 Donald Petrie
1068 Eric Brevig
1069 Garry Marshall
1070 Alan J. Pakula
1071 Joel Schumacher
1072 Rob Reiner
1073 Phillip Noyce
1074 Robert Luketic
1075 Denis Villeneuve
1076 Antoine Fuqua
1077 Dean Parisot
1078 Keenen Ivory Wayans
1079 James Bobin
1080 Stephen Norrington
1081 Thomas Carter
1082 Roger Michell
1083 Luis Llosa
1084 David McNally
1085 Richard Curtis
1086 John Lasseter
1087 Albert Hughes
1088 Luis Llosa
1089 Ron Shelton
1090 Melville Shavelson
1091 Jesse Dylan
1092 Garth Jennings
1093 Joel Zwick
1094 Russell Mulcahy
1095 Frank Coraci
1096 Wayne Wang
1097 Curtis Hanson
1098 Frank Oz
1099 Oliver Stone
1100 David R. Ellis
1101 Peter Howitt
1102 John A. Davis
1103 David Lynch
1104 Julie Taymor
1105 Sam Mendes
1106 Richard Donner
1107 Mathieu Kassovitz
1108 John Gray
1109 Harold Ramis
1110 John Schultz
1111 Sean Penn
1112 Susan Stroman
1113 Simon Wincer
1114 Billy Bob Thornton
1115 Oliver Stone
1116 Roman Polanski
1117 Stephen Sommers
1118 Spike Lee
1119 Yimou Zhang
1120 Danny Pang
1121 Barry Sonnenfeld
1122 Mike Newell
1123 nan
1124 George P. Cosmatos
1125 Oliver Parker
1126 Lawrence Kasanoff
1127 Ben Affleck
1128 Andrew Davis
1129 Andy Tennant
1130 Barry Levinson
1131 George P. Cosmatos
1132 Brian Gibson
1133 Norman Ferguson
1134 Michael Cimino
1135 Len Wiseman
1136 Paul McGuigan
1137 Gus Van Sant
1138 Betty Thomas
1139 Louis Leterrier
1140 Roger Kumble
1141 Sydney Pollack
1142 Burr Steers
1143 Simon West
1144 Phil Lord
1145 Roger Michell
1146 Peter Lord
1147 John Hamburg
1148 Reginald Hudlin
1149 Paul Feig
1150 Joseph L. Mankiewicz
1151 Frank Coraci
1152 Carl Franklin
1153 Barbra Streisand
1154 Mark Pellington
1155 Larry Charles
1156 John Glen
1157 Catherine Hardwicke
1158 John Herzfeld
1159 Annabel Jankel
1160 Andrew Niccol
1161 Yimou Zhang
1162 Julie Anne Robinson
1163 Evan Goldberg
1164 Sngmoo Lee
1165 nan
1166 Jean-Pierre Jeunet
1167 Curtis Hanson
1168 Jamel Debbouze
1169 Brian Helgeland
1170 Gordon Chan
1171 M. Night Shyamalan
1172 Asger Leth
1173 David Frankel
1174 John G. Avildsen
1175 David O. Russell
1176 Anne Fletcher
1177 Bruce Beresford
1178 Robert Zemeckis
1179 Luc Besson
1180 Sam Taylor-Johnson
1181 Robert Rodriguez
1182 Joel Schumacher
1183 Shawn Levy
1184 Peter Berg
1185 Penny Marshall
1186 James Wan
1187 David Fincher
1188 Ken Kwapis
1189 David Zucker
1190 Wes Craven
1191 Robert Zemeckis
1192 Etan Cohen
1193 Francis Ford Coppola
1194 Nora Ephron
1195 Brian Helgeland
1196 Anthony Minghella
1197 Bobby Farrelly
1198 Frank Marshall
1199 Nancy Meyers
1200 Tim Story
1201 Michael Mann
1202 Taylor Hackford
1203 Frank Miller
1204 Pete Travis
1205 John Hamburg
1206 Bobby Farrelly
1207 Oliver Stone
1208 John Whitesell
1209 Gore Verbinski
1210 Burr Steers
1211 Nick Cassavetes
1212 David R. Ellis
1213 Steven Spielberg
1214 John Moore
1215 Nicholas Stoller
1216 Peter Chelsom
1217 Joe Dante
1218 Mark A.Z. Dippé
1219 Kevin Reynolds
1220 Brad Furman
1221 Jaume Collet-Serra
1222 Christopher Nolan
1223 Sean Anders
1224 Cal Brunker
1225 Mel Gibson
1226 John Glen
1227 Nimród Antal
1228 Ivan Reitman
1229 David Koepp
1230 Alejandro Agresti
1231 Iain Softley
1232 Peter Hedges
1233 Paul Weiland
1234 Clint Eastwood
1235 Francis Ford Coppola
1236 Mathieu Kassovitz
1237 Steven Spielberg
1238 John McTiernan
1239 Colin Strause
1240 Donald Petrie
1241 Joan Chen
1242 Marc Lawrence
1243 Greg Mottola
1244 Anne Fletcher
1245 Wes Craven
1246 Joel Schumacher
1247 Oliver Stone
1248 Jake Kasdan
1249 Diane Keaton
1250 Steven Quale
1251 Kelly Makin
1252 Mimi Leder
1253 Bobby Farrelly
1254 nan
1255 Steven Brill
1256 Seth MacFarlane
1257 Russell Mulcahy
1258 Stephen Daldry
1259 Roger Michell
1260 Jim Sheridan
1261 Christian Duguay
1262 Chris Columbus
1263 Chuck Russell
1264 Sam Weisman
1265 John Frankenheimer
1266 Peter Hyams
1267 Justin Chadwick
1268 Pat O'Connor
1269 Stephen Hopkins
1270 Martin Scorsese
1271 Penny Marshall
1272 Olivier Megaton
1273 Frederik Du Chau
1274 Michael Caton-Jones
1275 Irwin Winkler
1276 Joseph Kahn
1277 Harold Becker
1278 Paul Verhoeven
1279 Sofia Coppola
1280 Barbet Schroeder
1281 Stephen Kay
1282 J.A. Bayona
1283 Elaine May
1284 Wes Anderson
1285 Stephen Herek
1286 John Carpenter
1287 Jean-Pierre Jeunet
1288 Dennie Gordon
1289 Charles Shyer
1290 Ken Kwapis
1291 Ulu Grosbard
1292 William Malone
1293 Paul Weitz
1294 Danny DeVito
1295 Malcolm D. Lee
1296 Jerry Jameson
1297 Mic Rodgers
1298 Christian Alvart
1299 Gary Fleder
1300 Christian Duguay
1301 Jean-Marie Poiré
1302 Danny Boyle
1303 Brian Robbins
1304 Marc F. Adler
1305 Pierre Morel
1306 Geoffrey Sax
1307 D.J. Caruso
1308 Iain Softley
1309 Richard Shepard
1310 Joel Coen
1311 Peter Ho-Sun Chan
1312 Sergey Bodrov
1313 Joon-ho Bong
1314 Bibo Bergeron
1315 Jeff Nathanson
1316 Alex Proyas
1317 S.S. Rajamouli
1318 Robert Schwentke
1319 Michael Lehmann
1320 Tim Burton
1321 Joss Whedon
1322 Charles S. Dutton
1323 Richard Lester
1324 Peter Segal
1325 John Woo
1326 Andy Tennant
1327 Robert Luketic
1328 Jonathan Lynn
1329 Robert Rodriguez
1330 David Carson
1331 Kar-Wai Wong
1332 Francis Lawrence
1333 nan
1334 Yuefeng Song
1335 Norman Jewison
1336 Michael Apted
1337 David Mirkin
1338 Andy Fickman
1339 Luis Mandoki
1340 John Pasquin
1341 Roman Polanski
1342 Michael Apted
1343 Stephen Herek
1344 Lee Daniels
1345 Ridley Scott
1346 John Carpenter
1347 David Twohy
1348 Jeb Stuart
1349 Steve Miner
1350 Gil Kenan
1351 Paul Thomas Anderson
1352 David Leland
1353 Gary Fleder
1354 J Blakeson
1355 Ryan Coogler
1356 Ben Affleck
1357 Kirk Jones
1358 Ethan Coen
1359 Jennifer Flackett
1360 Ron Howard
1361 Paul Thomas Anderson
1362 Kevin Smith
1363 Christian Ditter
1364 Charles Martin Smith
1365 Catherine Hardwicke
1366 Nick Cassavetes
1367 Les Mayfield
1368 Rawson Marshall Thurber
1369 Fedor Bondarchuk
1370 Jonathan Mostow
1371 Irvin Kershner
1372 Steve Pink
1373 Charles Martin Smith
1374 John Frankenheimer
1375 F. Gary Gray
1376 Cameron Crowe
1377 Rob Reiner
1378 Scott Hicks
1379 Mikael Håfström
1380 Andrew Niccol
1381 Andrew Bergman
1382 Kirk De Micco
1383 Chris Rock
1384 Todd Phillips
1385 Wilson Yip
1386 Jay Roach
1387 Tim Burton
1388 Roland Joffé
1389 Richard Donner
1390 John Lee Hancock
1391 nan
1392 Robert Rodriguez
1393 Seth Gordon
1394 Ethan Coen
1395 David Frankel
1396 Robert Wise
1397 Seth Gordon
1398 Martin Scorsese
1399 Robert Luketic
1400 Judd Apatow
1401 Kevin Rodney Sullivan
1402 Anthony Minghella
1403 Curtis Hanson
1404 Mike Mitchell
1405 Frank Oz
1406 Roger Donaldson
1407 Wes Craven
1408 Tarsem Singh
1409 Randall Wallace
1410 Randall Wallace
1411 Kevin Munroe
1412 Michael Tollin
1413 Will Gluck
1414 Nicholas Stoller
1415 John Lee Hancock
1416 Spike Lee
1417 Judd Apatow
1418 Walt Becker
1419 Patrick Tatopoulos
1420 Ken Kwapis
1421 Dennis Dugan
1422 Gary David Goldberg
1423 Mike Newell
1424 Paul W.S. Anderson
1425 Tobe Hooper
1426 Ethan Coen
1427 John Moore
1428 Andrew Niccol
1429 Alan Poul
1430 Luke Greenfield
1431 nan
1432 Gil Junger
1433 Michael Ritchie
1434 Steven E. de Souza
1435 Roman Polanski
1436 Catherine Hardwicke
1437 Jaume Collet-Serra
1438 Mike Nichols
1439 Clint Eastwood
1440 Alexandre Aja
1441 Michael Rymer
1442 Stephen Hopkins
1443 Gregory Hoblit
1444 Hugh Wilson
1445 Mike Hodges
1446 Kevin Smith
1447 Rob Cohen
1448 Clint Eastwood
1449 Scott Mann
1450 Susanna White
1451 Danny DeVito
1452 Chris Carter
1453 Tommy O'Haver
1454 Peter Landesman
1455 John Singleton
1456 Gary Chapman
1457 Curtis Hanson
1458 Craig Mazin
1459 Allen Hughes
1460 Wes Craven
1461 David Koepp
1462 Anne Fletcher
1463 Shekhar Kapur
1464 Taylor Hackford
1465 Richard Loncraine
1466 Roger Kumble
1467 Kimble Rendall
1468 Peter Yates
1469 Robert Redford
1470 John Milius
1471 Jake Kasdan
1472 Lasse Hallström
1473 Les Mayfield
1474 Jean-Marc Vallée
1475 Dominic Sena
1476 Terrence Malick
1477 Hark Tsui
1478 David Ayer
1479 Brian Helgeland
1480 Lexi Alexander
1481 Peter Hewitt
1482 Robert Zemeckis
1483 Ronny Yu
1484 Ridley Scott
1485 nan
1486 Richard Donner
1487 Taylor Hackford
1488 Bille August

1489 Brian De Palma
1490 Moustapha Akkad
1491 Jean-Paul Rappeneau
1492 Ang Lee
1493 Alejandro G. Iñárritu
1494 Joachim Rønning
1495 Tony Kaye
1496 Wes Ball
1497 Ken Scott
1498 Martin Scorsese
1499 Darren Aronofsky
1500 Hugh Johnson
1501 Simon West
1502 Hayao Miyazaki
1503 George Tillman Jr.
1504 Rand Ravich
1505 Hugh Hudson
1506 Gabriele Muccino
1507 Justin Chadwick
1508 Warren Beatty
1509 Rob Reiner
1510 Andrzej Bartkowiak
1511 Raja Gosnell
1512 Jeremy Degruson
1513 Chris Gorak
1514 Scott Speer
1515 David R. Ellis
1516 Joe Charbanic
1517 Jonathan Hensleigh
1518 Danny Cannon
1519 Boaz Yakin
1520 Mike Newell
1521 Richard Marquand
1522 Neil Marshall
1523 Stephen Daldry
1524 David Wain
1525 Jon Favreau
1526 Jon Turteltaub
1527 Brian Levant
1528 Richard Donner
1529 Jared Hess
1530 Paul Feig
1531 Evan Goldberg
1532 Rupert Wainwright
1533 George Tillman Jr.
1534 John Luessenhop
1535 Justin Zackham
1536 John Whitesell
1537 Duncan Jones
1538 Frank Marshall
1539 Joel Schumacher
1540 Jean-Pierre Jeunet
1541 Steven Spielberg
1542 John Gatins
1543 David Cronenberg
1544 Louis Leterrier
1545 Sam Raimi
1546 Peter Howitt
1547 Martin Scorsese
1548 Miguel Sapochnik
1549 Hyung-rae Shim
1550 Norman Jewison
1551 Don Scardino
1552 Mark Dindal
1553 Tim Robbins
1554 Steven Soderbergh
1555 Tom Reeve
1556 Francis Ford Coppola
1557 Nanette Burstein
1558 Stephen Herek
1559 Ariel Vromen
1560 Sydney Pollack
1561 Robert Zemeckis
1562 Lewis Gilbert
1563 Wes Anderson
1564 Scott Hicks
1565 Frank Marshall
1566 Gregory Hoblit
1567 John Francis Daley
1568 Barry Sonnenfeld
1569 Rob Marshall
1570 Dennis Dugan
1571 J.B. Rogers
1572 John Lasseter
1573 Jan de Bont
1574 Michael Sucsy
1575 Tom Vaughan
1576 Boaz Yakin
1577 John McTiernan
1578 Lee Daniels
1579 Rawson Marshall Thurber
1580 Barry Sonnenfeld
1581 Steve Oedekerk
1582 Garry Marshall
1583 Hugh Wilson
1584 David Fincher
1585 Neill Blomkamp
1586 Stephen Hillenburg
1587 Clint Eastwood
1588 Clint Eastwood
1589 Harold Ramis
1590 Nick Cassavetes
1591 Anne Fletcher
1592 Peter Chelsom
1593 Stig Bergqvist
1594 Barbra Streisand
1595 Edward Zwick
1596 Jason Reitman
1597 Alexander Payne
1598 Jonathan Levine
1599 Rian Johnson
1600 Chris Weitz
1601 Chris Noonan
1602 David Frankel
1603 Nicholas Stoller
1604 nan
1605 John Singleton
1606 Michael McCullers
1607 Forest Whitaker
1608 Gary Winick
1609 Steven Brill
1610 Gary Winick
1611 Woody Allen
1612 Peter Lepeniotis
1613 Ted Demme
1614 Luis Mandoki
1615 William Shatner
1616 John Schultz
1617 Peter Segal
1618 John Glen
1619 Steve Box
1620 Richard LaGravenese
1621 Frederik Du Chau
1622 Joe Wright
1623 Gary Winick
1624 Ridley Scott
1625 Bobby Farrelly
1626 Tim Burton
1627 James Gartner
1628 Denis Villeneuve
1629 Antoine Fuqua
1630 Sam Raimi
1631 Lee Toland Krieger
1632 Tim McCanlies
1633 Jon M. Chu
1634 John Stockwell
1635 Marc Forster
1636 David Slade
1637 Drew Goddard
1638 Jason Friedberg
1639 Martin Brest
1640 Paul Michael Glaser
1641 Frank Oz
1642 Joe Wright
1643 nan
1644 John R. Leonetti
1645 Tom Hanks
1646 Kimberly Peirce
1647 Liz Friedlander
1648 nan
1649 Phil Joanou
1650 Sam Weisman
1651 Shane Acker
1652 Steven Soderbergh
1653 Martha Coolidge
1654 Stephen J. Anderson
1655 Troy Miller
1656 Warren Beatty
1657 Tate Taylor
1658 Carl Franklin
1659 Brett Leonard
1660 Ivan Reitman
1661 Scott Derrickson
1662 Alister Grierson
1663 Nick Hurran
1664 Nicholas Stoller
1665 Charles Stone III
1666 Paul Haggis
1667 Kurt Wimmer
1668 Jean-François Richet
1669 Antoine Fuqua
1670 Kevin Hooks
1671 Ellory Elkayem
1672 Edward Zwick
1673 Jon Avnet
1674 Niki Caro
1675 Howard Deutch
1676 Vincenzo Natali
1677 Willard Huyck
1678 Gavin O'Connor
1679 Bruce Hunt
1680 Rob Reiner
1681 Paul McGuigan
1682 Craig Gillespie
1683 Terrence Malick
1684 Chris Roberts
1685 Neil Jordan
1686 James Wong
1687 Jee-woon Kim
1688 Nick Hamm
1689 Andy Cadiff
1690 Mike Disa
1691 Lasse Hallström
1692 Terry Gilliam
1693 Richard J. Lewis
1694 nan
1695 Brad Furman
1696 Peter Howitt
1697 Edward Zwick
1698 Sergio Leone
1699 Niels Arden Oplev
1700 Michael Radford
1701 Neil Jordan
1702 Steve Boyum
1703 Chris Noonan
1704 Kaige Chen
1705 Corey Yuen
1706 Andrew Dominik
1707 Li Zhang
1708 Laurent Tirard
1709 Simon West
1710 Marc Forster
1711 Reinhard Klooss
1712 Bille August
1713 Frédéric Auburtin
1714 Olivier Dahan
1715 Maksim Fadeev
1716 Liliana Cavani
1717 Greg Tiernan
1718 Elizabeth Banks
1719 James Mangold
1720 nan
1721 Edward Norton
1722 Peter Hewitt
1723 Ron Howard
1724 George Clooney
1725 Reginald Hudlin
1726 Ben Falcone
1727 Richard Attenborough
1728 Lawrence Kasdan
1729 Don Mancini
1730 John Maybury
1731 Ron Clements
1732 F. Gary Gray
1733 Steven Spielberg
1734 Igor Kovalyov
1735 Lee Tamahori
1736 Stephen Frears
1737 Robert Rodriguez
1738 John McTiernan
1739 David Wain
1740 Adam McKay
1741 Ang Lee
1742 Gavin O'Connor
1743 Zack Snyder
1744 Adam Shankman
1745 Shinji Aramaki
1746 Wes Anderson
1747 James Mangold
1748 Jon Turteltaub
1749 John Glen
1750 Peter Chelsom
1751 Peter Hyams
1752 Ben Stiller
1753 Lasse Hallström
1754 Kenny Ortega
1755 Scott Hicks
1756 Matthew Vaughn
1757 Ruben Fleischer
1758 Patrick Lussier
1759 Miguel Arteta
1760 Joe Wright
1761 Ridley Scott
1762 Michael Caton-Jones
1763 McG
1764 James Gray
1765 Janusz Kaminski
1766 Jacques Perrin
1767 Donald Petrie
1768 Jay Roach
1769 Brian Levant
1770 Michael Ritchie
1771 John Carpenter
1772 David Gordon Green
1773 Burr Steers
1774 Martin Scorsese
1775 Robert B. Weide
1776 Jeff Wadlow
1777 Agustín Díaz Yanes
1778 Camille Delamarre
1779 John Glen
1780 Judd Apatow
1781 Nick Cassavetes
1782 Malcolm D. Lee
1783 David Lean
1784 Richard Eyre
1785 Gavin Hood
1786 nan
1787 Nicholas Meyer
1788 Callie Khouri
1789 Gary Fleder
1790 John Landis
1791 Sanaa Hamri
1792 Todd Graff
1793 Chris Weitz
1794 Steve Miner
1795 Paul McGuigan
1796 Philip Kaufman
1797 Roland Emmerich
1798 Wolfgang Petersen
1799 Alex Proyas
1800 Saul Dibb
1801 nan
1802 Walter Murch
1803 Richard Linklater
1804 Christian Alvart
1805 E. Elias Merhige
1806 Menno Meyjes
1807 Robert Rodriguez
1808 Jodie Foster
1809 Ronny Yu
1810 Joel Schumacher
1811 Renny Harlin
1812 Barry Levinson
1813 Norman Jewison
1814 Kenneth Branagh
1815 Steve Carr
1816 Mark Waters
1817 Judd Apatow
1818 John Madden
1819 Scott Frank
1820 Ivan Reitman
1821 David Gordon Green
1822 Andy Tennant
1823 Kevin Costner
1824 Joel Schumacher
1825 nan
1826 Richard Attenborough
1827 Wes Craven
1828 David R. Ellis
1829 Joel Coen
1830 Scott Stewart
1831 Michael Bay
1832 Paul Weitz
1833 Jonathan Frakes
1834 Lawrence Kasdan
1835 Jim Sheridan
1836 Kevin Allen
1837 Garry Marshall
1838 Michael Cristofer
1839 James McTeigue
1840 Donald Petrie
1841 Andrew Morahan
1842 Bob Rafelson
1843 Michael Cohn
1844 Woody Allen
1845 David O. Russell
1846 Alan Shapiro
1847 Tarsem Singh
1848 Fernando Meirelles
1849 Mel Gibson
1850 Chris Columbus
1851 Barry Levinson
1852 Clint Eastwood
1853 Oliver Stone
1854 Pierre Morel
1855 Michael Hoffman
1856 Mick Jackson
1857 Steven Spielberg
1858 Tate Taylor
1859 Bill Condon
1860 Raja Gosnell
1861 Oleg Stepchenko
1862 Ronny Yu
1863 Michael Winterbottom
1864 John A. Davis
1865 Matt Reeves
1866 Michael Pressman
1867 Brian De Palma
1868 Ethan Coen
1869 Tim Story
1870 Sharon Maguire
1871 Lasse Hallström
1872 Charles Herman-Wurmfeld
1873 Andy Fickman
1874 Ivan Reitman
1875 George P. Cosmatos
1876 Andrzej Bartkowiak
1877 Richard Donner
1878 James Wong
1879 Scott Hicks
1880 Gabor Csupo
1881 Marc Forster
1882 Tyler Perry
1883 Joe Carnahan
1884 John Polson
1885 Adam McKay
1886 Martin Scorsese
1887 Harald Zwart
1888 Kirk Jones
1889 Brian De Palma
1890 Steve Oedekerk
1891 Bernardo Bertolucci
1892 Baltasar Kormákur
1893 Brett Ratner
1894 Paul Thomas Anderson
1895 Cathy Malkasian
1896 John Eng
1897 Malcolm D. Lee
1898 Ken Kwapis
1899 Chris Nahon
1900 Fred Wolf
1901 Bille Woodruff
1902 Craig Gillespie
1903 Phillip Noyce
1904 Dennie Gordon
1905 Victor Salva
1906 Mark Helfrich
1907 Andrzej Bartkowiak
1908 Stephen Daldry
1909 Andy Fickman
1910 Steve Bendelack
1911 Dwight H. Little
1912 Guillaume Canet
1913 Kirsten Sheridan
1914 Shekhar Kapur
1915 Ronny Yu
1916 Richard Fleischer
1917 Bob Spiers
1918 David Gordon Green
1919 Damien Dante Wayans
1920 Frank Darabont
1921 Simon Wincer
1922 Bobby Farrelly
1923 Rupert Wyatt
1924 John Wells
1925 Tim Fywell
1926 Nigel Cole
1927 Dexter Fletcher
1928 Spike Lee
1929 Jeremy Leven
1930 nan
1931 Lasse Hallström
1932 Sylvain White
1933 Troy Nixey
1934 Philip G. Atwell
1935 Paul Thomas Anderson
1936 Jeff Schaffer
1937 Don Michael Paul
1938 Paul Feig
1939 James Bridges
1940 Steve Barron
1941 Bill Paxton
1942 Richard Kelly
1943 Carter Smith
1944 John Schlesinger
1945 Wes Craven
1946 Luke Greenfield
1947 Ringo Lam
1948 Bruce McCulloch
1949 Brian Helgeland
1950 Akiva Schaffer
1951 David R. Ellis
1952 Alan Parker
1953 Ivan Reitman
1954 Tobe Hooper
1955 nan
1956 Robert Redford
1957 Catherine Hardwicke
1958 Patricia Riggen
1959 John Carpenter
1960 Pascal Chaumeil
1961 Gavin O'Connor
1962 Neil Jordan
1963 Ron Maxwell
1964 Kimberly Peirce
1965 Stephen Gaghan
1966 Jonathan Kaplan
1967 Ole Bornedal
1968 Richard Benjamin
1969 Rod Lurie
1970 Lasse Hallström
1971 Craig R. Baxley
1972 John Hillcoat
1973 John Guillermin
1974 Marcos Siega
1975 J.B. Rogers
1976 Roger Donaldson
1977 Rachel Talalay
1978 Jeffrey W. Byrd
1979 Fernando Meirelles
1980 Uwe Boll
1981 Roman Polanski
1982 Atom Egoyan
1983 Andrew Adamson
1984 Robert Towne
1985 Richard Linklater
1986 Giuseppe Tornatore
1987 Werner Herzog
1988 Ben Stassen
1989 Guillaume Canet
1990 Taylor Hackford
1991 Jérôme Deschamps
1992 Inna Evlannikova
1993 Ridley Scott
1994 Jonathan English
1995 Sergey Bondarchuk
1996 Teddy Chan
1997 Mario Van Peebles
1998 Stephen Frears
1999 Walter Salles
2000 Leonard Nimoy
2001 Sylvester Stallone
2002 Wes Craven
2003 Gavin O'Connor
2004 Tim Story
2005 Jonathan Lynn
2006 Herbert Ross
2007 Todd Phillips
2008 Terry Gilliam
2009 Danny Cannon
2010 Bonnie Hunt
2011 Kevin Smith
2012 Neil LaBute
2013 Grant Heslov
2014 George Gallo
2015 James Mangold
2016 Robert Luketic
2017 Tim Hill
2018 Sidney Lumet
2019 Brian Robbins
2020 Ron Shelton
2021 Douglas McGrath
2022 Alexandre Aja
2023 Kevin Spacey
2024 Steve Boyum
2025 Richard Williams
2026 Mary McGuckian
2027 George Tillman Jr.
2028 Hayao Miyazaki
2029 Ruben Fleischer
2030 Frank Coraci
2031 Irvin Kershner
2032 Michael Bay
2033 David Zucker
2034 James Wong
2035 George Clooney
2036 David Twohy
2037 Tony Goldwyn
2038 Spike Jonze
2039 John Dahl
2040 Jonathan Newman
2041 Wayne Wang
2042 Michael Dinner
2043 Steven Soderbergh
2044 Joseph Sargent
2045 Jerry Zaks
2046 Fred Durst
2047 Neil Jordan
2048 Simon Wincer
2049 Paul Haggis
2050 Anne Fontaine
2051 Jon Cassar
2052 Stephen Frears
2053 nan
2054 Mira Nair
2055 Teddy Chan
2056 Mikael Håfström
2057 Mel Brooks
2058 Russell Crowe
2059 Jerry Zucker
2060 Bobby Farrelly
2061 John Pasquin
2062 John Lee Hancock
2063 Andy Fickman
2064 Clint Eastwood
2065 Luke Greenfield
2066 Richard Attenborough
2067 Lasse Hallström
2068 Irwin Winkler
2069 Jessie Nelson
2070 Christopher Spencer
2071 Len Wiseman
2072 Mikael Håfström
2073 Steven Soderbergh
2074 Richard Attenborough
2075 Mike Bigelow
2076 Ken Scott
2077 Susanna White
2078 Dennis Dugan
2079 David Bowers
2080 Spike Lee
2081 Kevin Smith
2082 Daniel Sackheim
2083 Ethan Coen
2084 Harry Elfont
2085 Gary Fleder
2086 Uli Edel
2087 David O. Russell
2088 Fred Dekker
2089 Brian Trenchard-Smith
2090 Blake Edwards
2091 Hugh Wilson
2092 Camille Delamarre
2093 Laurence Dunmore
2094 Paul Verhoeven
2095 Christian Carion
2096 David Palmer
2097 Callie Khouri
2098 Rowan Joffe
2099 William Friedkin
2100 John Curran
2101 Laurent Tirard
2102 Scott Cooper
2103 Tony Gilroy
2104 Peter Segal
2105 Mark Pellington
2106 Juan José Campanella
2107 Woody Allen
2108 Clint Eastwood

2109 Trey Parker
2110 Frank Oz
2111 Stuart Gillard
2112 Brian Robbins
2113 David O. Russell
2114 Richard LaGravenese
2115 Tyler Perry
2116 Louis Leterrier
2117 Jeff Wadlow
2118 Katt Shea
2119 nan
2120 Sam Mendes
2121 Joshua Michael Stern
2122 Brad Silberling
2123 Tomas Alfredson
2124 John Duigan
2125 Jodie Foster
2126 Colin Higgins
2127 David Cronenberg
2128 Steven Spielberg
2129 Chris Columbus
2130 Steven Spielberg
2131 Jim Sonzero
2132 Tony Scott
2133 Adam Shankman
2134 Jonathan Demme
2135 Penelope Spheeris
2136 Jeff Tremaine
2137 Jeannot Szwarc
2138 Raja Gosnell
2139 James Wan
2140 Brian Levant
2141 Ben Falcone
2142 Richard Linklater
2143 Paul W.S. Anderson
2144 Keenen Ivory Wayans
2145 Alexander Payne
2146 Andrew Davis
2147 Julie Anne Robinson
2148 Steve McQueen
2149 Charles Stone III
2150 Tyler Perry
2151 Tim Burton
2152 Thea Sharrock
2153 Tyler Perry
2154 William Friedkin
2155 Jon Lucas
2156 Aaron Seltzer
2157 Robin Budd
2158 Ava DuVernay
2159 Steve Trenbirth
2160 Stephen Kay
2161 Mennan Yapo
2162 Jun Falkenstein
2163 Jaume Collet-Serra
2164 Boaz Yakin
2165 nan
2166 Jason Friedberg
2167 Tom McCarthy
2168 Neil LaBute
2169 Takashi Shimizu
2170 Kevin Rodney Sullivan
2171 Peter Hewitt
2172 Barry Levinson
2173 Gary Nelson
2174 Anton Corbijn
2175 Gregory Nava
2176 Jason Friedberg
2177 Alejandro G. Iñárritu
2178 Shawn Levy
2179 John Patrick Shanley
2180 Trey Parker
2181 John Luessenhop
2182 Jon Amiel
2183 Malcolm D. Lee
2184 Joshua Logan
2185 Gus Van Sant
2186 Kevin Reynolds
2187 Steve Beck
2188 Todd Strauss-Schulson
2189 John McNaughton
2190 Nelson McCormick
2191 John Madden
2192 Stephen Frears
2193 Eric Valette
2194 John Schlesinger
2195 Roger Donaldson
2196 Michel Gondry
2197 Andy Fickman
2198 David Ayer
2199 Edgar Wright
2200 Andrew Fleming
2201 Michael Spierig
2202 Jim Field Smith
2203 Thomas Bezucha
2204 William Brent Bell
2205 Simon Wincer
2206 Anthony Bell
2207 Renny Harlin
2208 Jessica Bendinger
2209 Robert Rodriguez
2210 Gus Van Sant
2211 Henry Joost
2212 Ed Harris
2213 John Carpenter
2214 nan
2215 Alfred Hitchcock
2216 Howard Deutch
2217 Shana Feste
2218 Garry Marshall
2219 Steve Rash
2220 Richard Donner
2221 Mark Steven Johnson
2222 Mike Binder
2223 Sean Penn
2224 Todd Phillips
2225 Michael J. Bassett
2226 Robert Rodriguez
2227 Frank Nissen
2228 Jodie Foster
2229 Stephen Chow
2230 nan
2231 Peter Hastings
2232 Marc Forster
2233 Alejandro G. Iñárritu
2234 Paul Abascal
2235 Chris Koch
2236 Amy Heckerling
2237 Michael Moore
2238 George Stevens
2239 Billy Ray
2240 Jason Friedberg
2241 Nimród Antal
2242 Jon Amiel
2243 Mark Mylod
2244 James Mather
2245 Barry Levinson
2246 Mark Neveldine
2247 Woody Allen
2248 Michael O. Sajbel
2249 Phillip Noyce
2250 Gore Verbinski
2251 Walter Hill
2252 David Koepp
2253 Renny Harlin
2254 Matt Reeves
2255 Charles T. Kanganis
2256 Michel Gondry
2257 Stephen Frears
2258 John Hillcoat
2259 Woody Allen
2260 Damon Santostefano
2261 John Wells
2262 Neil Jordan
2263 Woody Allen
2264 James Wan
2265 Kirk Jones
2266 Bob Clark
2267 Les Mayfield
2268 Les Mayfield
2269 Michael Lembeck
2270 Bob Fosse
2271 Paul Thomas Anderson
2272 Dave Borthwick
2273 Benson Lee
2274 nan
2275 David Zucker
2276 Robert Rodriguez
2277 Glen Morgan
2278 Fred Wolf
2279 Mike Leigh
2280 Alejandro Monteverde
2281 David Cronenberg
2282 Richard Linklater
2283 Michael Apted
2284 Uwe Boll
2285 Todd Graff
2286 Jonathan Glazer
2287 J.C. Chandor
2288 Paul Gross
2289 Marc Abraham
2290 Todd Haynes
2291 Mabrouk El Mechri
2292 Rian Johnson
2293 Charlie Kaufman
2294 Hayao Miyazaki
2295 Jean-Paul Rappeneau
2296 Nancy Walker
2297 John Hillcoat
2298 Angelo Pizzo
2299 Richard Benjamin
2300 Kurt Wimmer
2301 Roger Spottiswoode
2302 James Gray
2303 Matthew Diamond
2304 Angelina Jolie Pitt
2305 Katsuhiro Ôtomo
2306 David Anspaugh
2307 Andrew Jarecki
2308 Kevin Reynolds
2309 Stephen Chow
2310 Jean-Marie Poiré
2311 Kevin Munroe
2312 Daniel Algrant
2313 nan
2314 Julie Taymor
2315 Alejandro Amenábar
2316 Jane Clark
2317 Daniel Lee
2318 Mike Barker
2319 Wayne Thornley
2320 Gnana Rajasekaran
2321 Tom Walsh
2322 Jonathan Jakubowicz
2323 James McTeigue
2324 Scott Walker
2325 John Curran
2326 Uli Edel
2327 Kevin Costner
2328 Jake Kasdan
2329 Harold Becker
2330 Mark Rosman
2331 Wes Craven
2332 Steve Beck
2333 Stanley Kubrick
2334 Robert Zemeckis
2335 William Malone
2336 Tyler Perry
2337 Rob Hawk
2338 Josh Gordon
2339 Shawn Levy
2340 Lee Tamahori
2341 nan
2342 Britt Allcroft
2343 Breck Eisner
2344 Hayao Miyazaki
2345 Alan Yuen
2346 Roger Donaldson
2347 Brian Percival
2348 Sean Anders
2349 Anand Tucker
2350 Anthony Mann
2351 Michael Dowse
2352 Daniel Barnz
2353 Emile Ardolino
2354 Robert Altman
2355 James Schamus
2356 Andrew Douglas
2357 Spike Jonze
2358 George A. Romero
2359 Danny Pang
2360 Terry Gilliam
2361 Ricky Gervais
2362 Nicholas Stoller
2363 Chuck Russell
2364 Penny Marshall
2365 Larry Charles
2366 Robert Luketic
2367 Leonard Nimoy
2368 Scott Derrickson
2369 Mike Mitchell
2370 Vic Armstrong
2371 Thomas Bezucha
2372 Kevin Rodney Sullivan
2373 Terry Zwigoff
2374 Jay Roach
2375 Kirk Jones
2376 David Bowers
2377 John McTiernan
2378 Milos Forman
2379 Nelson McCormick
2380 Mark Waters
2381 Audrey Wells
2382 Robert Altman
2383 nan
2384 Francis Ford Coppola
2385 Alejandro G. Iñárritu
2386 Woody Allen
2387 Paul Greengrass
2388 Bille Woodruff
2389 Rick Friedberg
2390 John Carpenter
2391 Sean McNamara
2392 Mike Nichols
2393 Jody Hill
2394 Richard Fleischer
2395 Martin Scorsese
2396 Brandon Camp
2397 Barry Levinson
2398 Kevin Tancharoen
2399 Danny Boyle
2400 Woody Allen
2401 Nicholas Hytner
2402 Jessie Nelson
2403 Bart Freundlich
2404 Irwin Winkler
2405 Danny Boyle
2406 Chris Columbus
2407 Miguel Arteta
2408 William A. Fraker
2409 John Boorman
2410 Brian De Palma
2411 Courtney Solomon
2412 Ang Lee
2413 Rob Reiner
2414 Jeff Kanew
2415 István Szabó
2416 Adrian Lyne
2417 Matthew Robbins
2418 Michael Hoffman
2419 Tim Burton
2420 Jason Reitman
2421 Sergey Bodrov
2422 Guy Ritchie
2423 Hal Needham
2424 Kenneth Branagh
2425 Bruce Beresford
2426 Jeff Nichols
2427 Woody Allen
2428 Jonathan Teplitzky
2429 nan
2430 Michael Haneke
2431 Zack Ward
2432 Mike Marvin
2433 D.J. Caruso
2434 Nimród Antal
2435 Gregor Jordan
2436 nan
2437 Tran Anh Hung
2438 Lance Hool
2439 George A. Romero
2440 Chuck Russell
2441 Christian Volckman
2442 Richard Fleischer
2443 Rodrigo Cortés
2444 Greg Mottola
2445 Tyler Perry
2446 David Hayter
2447 Jon M. Chu
2448 Cory Edwards
2449 Terry George
2450 Xavier Gens
2451 Kasi Lemmons
2452 Brian A Miller
2453 Matt Dillon
2454 Alejandro Amenábar
2455 James Cameron
2456 George Cukor
2457 Jim Gillespie
2458 Luke Greenfield
2459 Alexander Payne
2460 Jay Chandrasekhar
2461 John Carpenter
2462 John Hoffman
2463 Malcolm D. Lee
2464 Joe Carnahan
2465 Kevin Greutert
2466 Michael Lehmann
2467 John Fortenberry
2468 Daniel Barnz
2469 Alexandre Aja
2470 Sam Weisman
2471 Niki Caro
2472 Erik White
2473 Chris Robinson
2474 Jason Moore
2475 Michael Tollin
2476 Sam Raimi
2477 Robert Harmon
2478 Trent Cooper
2479 Gary Halvorson
2480 Antoine Fuqua
2481 Nicholas Ray
2482 Fede Alvarez
2483 Donald Petrie
2484 Paul Weitz
2485 Sidney J. Furie
2486 Ian Iqbal Rashid
2487 Wayne Kramer
2488 Rowdy Herrington
2489 Jim Goddard
2490 Neil Burger
2491 Noel Marshall
2492 Joel Schumacher
2493 Andrea Di Stefano
2494 Richard Kelly
2495 Guillaume Ivernel
2496 Jack Smight
2497 Todd Lincoln
2498 Howard Zieff
2499 Steven Shainberg
2500 Oliver Stone
2501 Ang Lee
2502 Julian Jarrold
2503 Joe Nussbaum
2504 Vadim Perelman
2505 Peter Weir
2506 Peter Farrelly
2507 Rob Reiner
2508 Sidney Lumet
2509 Todd Phillips
2510 Brian Robbins
2511 Michel Hazanavicius
2512 David S. Goyer
2513 Wes Anderson
2514 Jonathan Liebesman
2515 Cyrus Nowrasteh
2516 Perry Andelin Blake
2517 Guillermo del Toro
2518 nan
2519 John Whitesell
2520 John Singleton
2521 Christian E. Christiansen
2522 Dennie Gordon
2523 Sheldon Lettich
2524 Edgar Wright
2525 Diane English
2526 Woody Allen
2527 Peter Flinth
2528 Robert Iscove
2529 Peter Kosminsky
2530 Karyn Kusama
2531 Nick Gomez
2532 Woody Allen
2533 Allen Coulter
2534 Clare Kilner
2535 Richard Benjamin
2536 Jonathan Demme
2537 Josef Rusnak
2538 Lance Rivera
2539 Ronald Neame
2540 Bruce Paltrow
2541 Woody Allen
2542 Adam Rifkin
2543 Russell Mulcahy
2544 Susanne Bier
2545 Kenneth Johnson
2546 James Gray
2547 James Ivory
2548 Danny Boyle
2549 Jessy Terrero
2550 Dany Boon
2551 Vicente Amorim
2552 Gaspar Noé
2553 Amy Heckerling
2554 Lasse Hallström
2555 Jérôme Salle
2556 Tommy Lee Jones
2557 Jesse Vaughan
2558 nan
2559 Atom Egoyan
2560 William Bindley
2561 Wayne Beach
2562 Gérard Krawczyk
2563 James Gunn
2564 Martin Brest
2565 Chris Columbus
2566 Leonard Nimoy
2567 Sydney Pollack
2568 Tony Scott
2569 Ang Lee
2570 Sam Mendes
2571 Tom Hooper
2572 Ivan Reitman
2573 nan
2574 Udayan Prasad
2575 Steven Spielberg
2576 JK Youn
2577 Morten Tyldum
2578 Howard Zieff
2579 Michael Apted
2580 Thor Freudenthal
2581 Andrés Muschietti
2582 Harold Ramis
2583 Jeff Tremaine
2584 Stephen Frears
2585 Tim Burton
2586 Tyler Perry
2587 Gillian Armstrong
2588 James Watkins
2589 Simon West
2590 Shawn Levy
2591 Michael Cimino
2592 Barry Levinson
2593 Jim Fall
2594 Ric Roman Waugh
2595 Michael Dougherty
2596 Robert Rodriguez
2597 Brian Gibson
2598 James Mangold
2599 Joel Gallen
2600 David Ayer
2601 Rob Cohen
2602 James Marsh
2603 John Whitesell
2604 Matt Williams
2605 David Lean
2606 Rob Zombie
2607 Jean-Marc Vallée
2608 Dennis Iliadis
2609 Clare Kilner
2610 Rick Rosenthal
2611 Rob Reiner
2612 Denzel Washington
2613 Nicolas Winding Refn
2614 Sara Sugarman
2615 Nicholas Hytner
2616 Juan Carlos Fresnadillo
2617 Thomas Carter
2618 Wayne Wang
2619 Gina Prince-Bythewood
2620 George Armitage
2621 Phil Traill
2622 Joe Berlinger
2623 Andrew Fleming
2624 Woody Allen
2625 Elizabeth Allen Rosenbaum
2626 James Ivory
2627 Paul Thomas Anderson
2628 Robert Harmon
2629 Michael Mayer
2630 Martin Weisz
2631 John Ottman
2632 Jay Russell
2633 John Bonito
2634 Peter Atencio
2635 Shana Feste
2636 David Nutter
2637 Derek Cianfrance
2638 Roger Donaldson
2639 Stephan Elliott
2640 Kathryn Bigelow
2641 Mark L. Lester
2642 Andrew Dominik
2643 Anton Corbijn
2644 Tom Green
2645 Mike Nawrocki
2646 Catherine Owens
2647 Douglas Aarniokoski
2648 Bryan Barber
2649 Lone Scherfig
2650 Drew Barrymore
2651 Brian Koppelman
2652 James Foley
2653 Albert Brooks
2654 Irwin Winkler
2655 Woody Allen
2656 Steve Gomer
2657 RZA
2658 Dean Parisot
2659 Mark Piznarski
2660 Terry Gilliam
2661 Sean McNamara
2662 nan
2663 Joel Coen
2664 Craig Brewer
2665 Ron Shelton
2666 Michael Winterbottom
2667 David Raynr
2668 Mort Nathan
2669 Oliver Parker
2670 Dan Curtis
2671 Wil Shriner
2672 Martin McDonagh
2673 Tina Gordon Chism
2674 Peter Cattaneo
2675 Vicky Jenson
2676 Gus Van Sant
2677 Woody Allen
2678 Mary Lambert
2679 Tommy Lee Jones
2680 Peter Kassovitz
2681 Shane Black
2682 Rodman Flender
2683 David Lynch
2684 Katja von Garnier
2685 Woody Allen
2686 Mark Romanek
2687 nan
2688 Brad Anderson
2689 Michael Chapman
2690 Antonio Banderas
2691 Michael Haneke
2692 Khalil Sullins
2693 Atom Egoyan
2694 Fritz Lang
2695 Pierre Morel
2696 Gary Fleder
2697 Hsiao-Hsien Hou
2698 Gregor Jordan
2699 Andrey Zvyagintsev
2700 Tony Jaa
2701 Neil Marshall
2702 Russell Mulcahy
2703 Ryûhei Kitamura
2704 Darrell Roodt
2705 Dito Montiel
2706 Stefan Ruzowitzky
2707 Jake Paltrow
2708 Juraj Jakubisko
2709 Anthony Silverston
2710 Gabe Ibáñez
2711 Gerry Lively
2712 Daniele Luchetti
2713 Tung-Shing Yee
2714 Julien Temple
2715 Harold Ramis
2716 Gregory Jacobs
2717 Baz Luhrmann
2718 Gilles Paquet-Brenner
2719 Peter Cousens
2720 Clint Eastwood
2721 Lars von Trier
2722 Danny Boyle
2723 Adrian Lyne
2724 Garry Marshall

2725 John Blanchard
2726 John Cornell
2727 Vidhu Vinod Chopra
2728 Oliver Stone
2729 Jon Turteltaub
2730 Patrick Lussier
2731 Sylvain White
2732 Lewis Gilbert
2733 nan
2734 Jamie Blanks
2735 Tyler Perry
2736 Randal Kleiser
2737 Bruce McCulloch
2738 Phyllida Lloyd
2739 Mike Nawrocki
2740 John Singleton
2741 Kevin Bray
2742 Wes Craven
2743 John Boorman
2744 Courtney Solomon
2745 David Zucker
2746 David Twohy
2747 Rick Famuyiwa
2748 Alan Cohn
2749 Franco Zeffirelli
2750 Tom Holland
2751 Martin Scorsese
2752 Spike Lee
2753 Chris Rock
2754 James Isaac
2755 Emilio Estevez
2756 Mark Waters
2757 Josh Schwartz
2758 Julian Schnabel
2759 Todd Field
2760 Davis Guggenheim
2761 Tony Goldwyn
2762 Phillip Noyce
2763 Stephen Carpenter
2764 James Ivory
2765 Stephan Elliott
2766 James Fargo
2767 Mike Leigh
2768 Alain Resnais
2769 Costa-Gavras
2770 Chao-Bin Su
2771 Neil Burger
2772 Kenneth Lonergan
2773 Bo Zenga
2774 Rob Reiner
2775 Ang Lee
2776 Amy Heckerling
2777 Todd Haynes
2778 Steve Pink
2779 nan
2780 Philip Kaufman
2781 Martin McDonagh
2782 Kasi Lemmons
2783 nan
2784 Oliver Hirschbiegel
2785 Alejandro Amenábar
2786 Jonathan Glazer
2787 Barry Levinson
2788 Hyung-rae Shim
2789 Jon M. Chu
2790 Darren Aronofsky
2791 Francis Ford Coppola
2792 Thomas Carter
2793 Renny Harlin
2794 Patricia Riggen
2795 Danny Leiner
2796 Christopher Cain
2797 Theodore Melfi
2798 Steve Pink
2799 Gil Junger
2800 Ed Decter
2801 Gene Quintano
2802 Jaume Collet-Serra
2803 Eric Bress
2804 Chris Koch
2805 Preston A. Whitmore II
2806 Bob Clark
2807 Kirk Wong
2808 Bronwen Hughes
2809 John Lafia
2810 Sam Miller
2811 Frank Darabont
2812 Alex Garland
2813 Spike Jonze
2814 Mark Brown
2815 Dave Green
2816 John Stockwell
2817 Clint Eastwood
2818 Michael Polish
2819 Daisy von Scherler Mayer
2820 Lenny Abrahamson
2821 Bob Saget
2822 John Waters
2823 Andrew Fleming
2824 Niels Arden Oplev
2825 Craig Bolotin
2826 Mark Christopher
2827 Blair Hayes
2828 Jez Butterworth
2829 Jon Lucas
2830 Olivier Assayas
2831 Rod Lurie
2832 Paul Weitz
2833 Patrice Leconte
2834 Atom Egoyan
2835 Paul Mazursky
2836 Sidney Lumet
2837 Stephen Chbosky
2838 Jon Hess
2839 Douglas McGrath
2840 Michael Winterbottom
2841 Mark Neveldine
2842 Joe Cornish
2843 Angelina Jolie Pitt
2844 Brad Anderson
2845 John H. Lee
2846 John Stainton
2847 Glenn Ficarra
2848 Jean-Jacques Annaud
2849 Denzel Washington
2850 Michael Hoffman
2851 Tony Scott
2852 Benedek Fliegauf
2853 James Foley
2854 Michael Winterbottom
2855 Paul Schrader
2856 Stewart Hendler
2857 John Cromwell
2858 Craig Gillespie
2859 Mark Herman
2860 Lars von Trier
2861 Gillian Armstrong
2862 Abel Ferrara
2863 Brian Koppelman
2864 Ethan Maniquis
2865 George Hickenlooper
2866 Don Bluth
2867 Je-kyu Kang
2868 William Dear
2869 William Friedkin
2870 Steven Spielberg
2871 Paul Weitz
2872 Stéphane Aubier
2873 Michael Ritchie
2874 Tim Story
2875 Tim Story
2876 Nicholas Meyer
2877 Tom Shadyac
2878 John Badham
2879 Peter Weir
2880 Mike McCoy
2881 Anne Fletcher
2882 Mike Judge
2883 Quentin Tarantino
2884 Jon Hurwitz
2885 Josh Trank
2886 Barbra Streisand
2887 Terry Gilliam
2888 Tamra Davis
2889 Nima Nourizadeh
2890 Franklin J. Schaffner
2891 Mark Romanek
2892 John Erick Dowdle
2893 David Moreau
2894 Christopher Erskin
2895 Jesse Dylan
2896 Brian Henson
2897 Julie Taymor
2898 Dan Cutforth
2899 Josh Boone
2900 John Dahl
2901 Chris Rock
2902 John Frankenheimer
2903 David Koepp
2904 nan
2905 Stephen Frears
2906 Mike Binder
2907 Franklin J. Schaffner
2908 Elizabeth Allen Rosenbaum
2909 Jake Schreier
2910 Cheryl Dunye
2911 Alexander Payne
2912 Ernest R. Dickerson
2913 Tim Hill
2914 Jason Reitman
2915 Mark Neveldine
2916 Lionel C. Martin
2917 Richard LaGravenese
2918 Sanaa Hamri
2919 Jonathan Demme
2920 Bob Rafelson
2921 Peter Webber
2922 Wolfgang Petersen
2923 Wallace Wolodarsky
2924 Richard Curtis
2925 Yimou Zhang
2926 Nicholas Jarecki
2927 Dean Israelite
2928 Darnell Martin
2929 Scott Alexander
2930 Stuart Gordon
2931 Christopher Guest
2932 Woody Allen
2933 Ryan Murphy
2934 Robert Iscove
2935 Spike Lee
2936 Jane Campion
2937 James Gray
2938 Fred Schepisi
2939 Roger Spottiswoode
2940 Antonia Bird
2941 Jon Poll
2942 Paolo Sorrentino
2943 Peter Care
2944 Chan-wook Park
2945 Kar-Wai Wong
2946 Ira Sachs
2947 Carroll Ballard
2948 Neil Jordan
2949 Takeshi Kitano
2950 Anthony Russo
2951 Sidney Lumet
2952 Vadim Perelman
2953 Lawrence Kasdan
2954 Marco Kreuzpaintner
2955 Lajos Koltai
2956 Alan Rudolph
2957 Yimou Zhang
2958 Vincenzo Natali
2959 Chuan Lu
2960 Lijun Sun
2961 Takashi Yamazaki
2962 Renny Harlin
2963 Christopher Smith
2964 Timothy Hines
2965 Randall Wallace
2966 Guy Ritchie
2967 David Winters
2968 Mary Lambert
2969 Akira Kurosawa
2970 Jamie Thraves
2971 Mabel Cheung
2972 Joe Dante
2973 George Lucas
2974 Dan Mazer
2975 David Lean
2976 Stephen Daldry
2977 Kenny Ortega
2978 David O. Russell
2979 Jeff Tremaine
2980 Jonathan Lynn
2981 R.J. Cutler
2982 Brian Trenchard-Smith
2983 David S. Ward
2984 Oliver Parker
2985 Joel Schumacher
2986 Adam Shankman
2987 Tim Robbins
2988 Roger Kumble
2989 Kevin Greutert
2990 Mel Brooks
2991 Gina Prince-Bythewood
2992 Rob Pritts
2993 Brian De Palma
2994 Norman Jewison
2995 Tobe Hooper
2996 John Crowley
2997 Stanley Kubrick
2998 Brendan Malloy
2999 Reginald Hudlin
3000 Dustin Hoffman
3001 Gregory Poirier
3002 Bill Paxton
3003 Simon Curtis
3004 Bill Condon
3005 Sam Raimi
3006 Dewey Nicks
3007 Lasse Hallström
3008 Philip Saville
3009 Mike Leigh
3010 Daisy von Scherler Mayer
3011 Mira Nair
3012 Ethan Coen
3013 Tim Blake Nelson
3014 William A. Graham
3015 Martin Ritt
3016 John Turturro
3017 Agnieszka Holland
3018 Rowan Joffe
3019 David Hackl
3020 Giuliano Montaldo
3021 Lisa Azuelos
3022 Ray Lawrence
3023 Karan Johar
3024 Oliver Parker
3025 Ruairi Robinson
3026 Jaume Balagueró
3027 Stanley Kubrick
3028 Steven Spielberg
3029 Jon Kasdan
3030 Léa Pool
3031 Floyd Mutrux
3032 nan
3033 Sajid Khan
3034 Christopher Cain
3035 Dean Wright
3036 Eric Lartigau
3037 Gus Van Sant
3038 Shintaro Shimosawa
3039 Darren Lynn Bousman
3040 Ivan Reitman
3041 Peyton Reed
3042 James DeMonaco
3043 Robert Iscove
3044 Darren Lynn Bousman
3045 Geoffrey Sax
3046 Tyler Perry
3047 Martin Scorsese
3048 Ken Annakin
3049 Stephen Herek
3050 Takashi Shimizu
3051 Dennis Dugan
3052 Victor Salva
3053 Stephen Herek
3054 Carol Reed
3055 John Madden
3056 Chuck Sheetz
3057 George Miller
3058 Mark L. Lester
3059 William Brent Bell
3060 John Erick Dowdle
3061 Marcus Raboy
3062 Leigh Whannell
3063 Michael Schultz
3064 Brett Leonard
3065 Peter Sollett
3066 Kevin Smith
3067 Bob Dolman
3068 Joe Dante
3069 Rowdy Herrington
3070 Keenen Ivory Wayans
3071 John Polson
3072 Greg Coolidge
3073 Harry Elfont
3074 Francis Ford Coppola
3075 David Lowery
3076 Ciarán Foy
3077 Salim Akil
3078 Jamie Blanks
3079 Olatunde Osunsanmi
3080 Robert Altman
3081 Leon Ichaso
3082 Joseph Zito
3083 Malcolm D. Lee
3084 Wes Anderson
3085 Colin Strause
3086 John Madden
3087 Patricia Rozema
3088 Mark Rosman
3089 Spike Lee
3090 Steve Oedekerk
3091 Ron Underwood
3092 Rob Schmidt
3093 Walter Hill
3094 James Foley
3095 Jeff Nichols
3096 Robert Ben Garant
3097 Morgan Spurlock
3098 Neal Brennan
3099 Tuck Tucker
3100 Simon Curtis
3101 Richard Shepard
3102 Theodore Witcher
3103 Joel Edgerton
3104 Jim Hanon
3105 Tommy O'Haver
3106 Mike Judge
3107 Michael Patrick Jann
3108 Tim Burton
3109 Peter Berg
3110 Joe Nussbaum
3111 Brian De Palma
3112 Jorma Taccone
3113 Stephen Frears
3114 Elizabeth Banks
3115 Jeff Lowell
3116 Lorene Scafaria
3117 Miguel Arteta
3118 nan
3119 Tony Kaye
3120 Marcus Dunstan
3121 Timothy Björklund
3122 François Girard
3123 David Lynch
3124 Scott Kalvert
3125 Jason Bateman
3126 David Schwimmer
3127 Allan Arkush
3128 Mike Binder
3129 Eric Bross
3130 Werner Herzog
3131 Dan Fogelman
3132 Jay Duplass
3133 Luca Guadagnino
3134 John Putch
3135 Peter Medak
3136 Steven Soderbergh
3137 Paul Haggis
3138 Terence Davies
3139 Harley Cokeliss
3140 Victor Salva
3141 Tom Brady
3142 Spike Lee
3143 Jason Zada
3144 Franklin J. Schaffner
3145 Noah Baumbach
3146 Chris Weitz
3147 David Cronenberg
3148 Eric Blakeney
3149 Douglas McGrath
3150 Ariel Vromen
3151 Rakesh Roshan
3152 John Waters
3153 William Friedkin
3154 Derrick Borte
3155 Richard Kwietniowski
3156 Bob Odenkirk
3157 Kar-Wai Wong
3158 John Turturro
3159 Guy Ritchie
3160 Joshua Seftel
3161 Stephen Chow
3162 Vincent Gallo
3163 Claude Chabrol
3164 Jon Stewart
3165 Bigas Luna
3166 Ralph Fiennes
3167 Dan Harris
3168 Mel Smith
3169 Bobcat Goldthwait
3170 Christopher Smith
3171 Stuart Gordon
3172 Jake Scott
3173 Alan Metter
3174 Jeb Stuart
3175 Rafa Lara
3176 Michael Radford
3177 Arthur Hiller
3178 Michael Meredith
3179 Julio DePietro
3180 Katherine Dieckmann
3181 William Dear
3182 Kim Farrant
3183 Marcus Raboy
3184 Scott Marshall
3185 Álex de la Iglesia
3186 Andrew Traucki
3187 Michael Clancy
3188 Patrick Lussier
3189 Robert Adetuyi
3190 Kari Skogland
3191 Taedong Park
3192 Paul Schrader
3193 Benedikt Erlingsson
3194 Gurinder Chadha
3195 Jason Connery
3196 Vic Sarin
3197 Jim Issa
3198 Jee-woon Kim
3199 Douglas Aarniokoski
3200 William Phillips
3201 Greg Mottola
3202 Andy Garcia
3203 Steve Carr
3204 Sarik Andreasyan
3205 Lewis Gilbert
3206 Julian Gilbey
3207 Michael Haneke
3208 Gary Sherman
3209 Valeri Milev
3210 Stanley Kramer
3211 Pedro Almodóvar
3212 Gerald Potterton
3213 Jared Hess
3214 Richard Loncraine
3215 David Hackl
3216 Anurag Basu
3217 Lars von Trier
3218 Kriv Stenders
3219 Yash Chopra
3220 Ridley Scott
3221 Tobe Hooper
3222 Floria Sigismondi
3223 Norman Jewison
3224 Terence Young
3225 Joseph Kahn
3226 Ferzan Ozpetek
3227 F. Gary Gray
3228 Malcolm D. Lee
3229 Tom Holland
3230 Michael Moore
3231 James DeMonaco
3232 Kris Isacsson
3233 Danny Leiner
3234 Rod Lurie
3235 Ben Younger
3236 John Landis
3237 Glen Morgan

3238 Daniel Taplitz
3239 Kenneth Branagh
3240 Tamara Jenkins
3241 Linda Mendoza
3242 Christopher McQuarrie
3243 Burr Steers
3244 Hart Bochner
3245 Michael O. Sajbel
3246 nan
3247 Stewart Raffill
3248 Davis Guggenheim
3249 Bart Freundlich
3250 Andrew Fleming
3251 Todd Haynes
3252 Hong-jin Na
3253 Kevin Tancharoen
3254 Chatrichalerm Yukol
3255 Dario Argento
3256 Eric Lavaine
3257 Mike Leigh
3258 Marc Forby
3259 Peter Cattaneo
3260 Ole Christian Madsen
3261 Meiert Avis
3262 Julian Jarrold
3263 André Téchiné
3264 Emily Young
3265 Peter Faiman
3266 Martyn Pick
3267 Roland Suso Richter
3268 Jeremy Sims
3269 Maïwenn
3270 Joby Harold
3271 nan
3272 Ekachai Uekrongtham
3273 Joel Schumacher
3274 Scott Cooper
3275 Mark Rydell
3276 David E. Talbert
3277 Roger Vadim
3278 Nils Gaup
3279 Alexander Payne
3280 Mira Nair
3281 Ari Sandel
3282 Vondie Curtis-Hall
3283 Tom Elkins
3284 Woo-Suk Kang
3285 Jane Campion
3286 Karan Johar
3287 J.C. Chandor
3288 John Sayles
3289 Vipul Amrutlal Shah
3290 Ken Loach
3291 Ayan Mukerji
3292 Mervyn LeRoy
3293 Darren Lynn Bousman
3294 Serdar Akar
3295 Quentin Tarantino
3296 James Frawley
3297 Dan Gilroy
3298 Jay Chandrasekhar
3299 Robert Wise
3300 Ron Howard
3301 Jonathan Dayton
3302 Rob Reiner
3303 Danny Boyle
3304 Chris Stokes
3305 Don Siegel
3306 Rick Famuyiwa
3307 Martin Lawrence
3308 Jonathan Levine
3309 Masayuki Ochiai
3310 Tom Gormican
3311 Ken Shapiro
3312 Justin Tipping
3313 Kenneth Branagh
3314 Peter R. Hunt
3315 nan
3316 Wes Craven
3317 John Schultz
3318 Doug Atchison
3319 Tamra Davis
3320 Jonas Elmer
3321 Mary Harron
3322 Miguel Arteta
3323 Erik Canuel
3324 Troy Duffy
3325 James Ivory
3326 Nicole Holofcener
3327 Will Gluck
3328 Matty Rich
3329 E. Elias Merhige
3330 Joe Nussbaum
3331 Matt Reeves
3332 Steve Rash
3333 Fina Torres
3334 James Ivory
3335 nan
3336 Duke Johnson
3337 Mike Leigh
3338 François Ozon
3339 Mark L. Lester
3340 David Dobkin
3341 Anna Boden
3342 Nigel Cole
3343 Anand Tucker
3344 Steve James
3345 Michael Winner
3346 Tomm Moore
3347 John Carney
3348 David Jacobson
3349 Michael Corrente
3350 Edward Hall
3351 Keith Gordon
3352 David Leland
3353 Andrew Currie
3354 Andrew Wilson
3355 Jonathan Lynn
3356 Marc Schölermann
3357 nan
3358 Robert Moresco
3359 Thomas Vinterberg
3360 Claudia Llosa
3361 Katsuhiro Ôtomo
3362 John Herzfeld
3363 Charles Binamé
3364 Keith Parmer
3365 Dennie Gordon
3366 Ol Parker
3367 Bruce Beresford
3368 François Ozon
3369 James Nunn
3370 David Webb Peoples
3371 Michael Winnick
3372 Bruce Beresford
3373 George Tillman Jr.
3374 Stanley Tong
3375 David Oelhoffen
3376 Jason Reitman
3377 Eli Roth
3378 Lone Scherfig
3379 Anand Tucker
3380 Tony Richardson
3381 Joe Carnahan
3382 Paul Gross
3383 Charles Robert Carner
3384 Russell Holt
3385 Mike Judge
3386 Larry Charles
3387 Claude Miller
3388 Michael Winterbottom
3389 Sacha Bennett
3390 Rodrigo García
3391 Jeta Amata
3392 Siddharth Anand
3393 Vincent Paronnaud
3394 Joe Dante
3395 Dennis Gansel
3396 Nicolas Winding Refn
3397 Daniel Barber
3398 Robert Marcarelli
3399 Jason Reitman
3400 Ernie Barbarash
3401 Guy Hamilton
3402 Francis Ford Coppola
3403 Adrian Lyne
3404 Marc Webb
3405 Jane Campion
3406 Steven Soderbergh
3407 Jonathan Liebesman
3408 Guy Hamilton
3409 Jay Russell
3410 Adam Brooks
3411 Salim Akil
3412 George Clooney
3413 Bennett Miller
3414 Robert Rodriguez
3415 nan
3416 Michael Anderson
3417 Guy Hamilton
3418 Craig R. Baxley
3419 Neil Marshall
3420 Don Kempf
3421 Matt Bettinelli-Olpin
3422 David O. Russell
3423 Rob Zombie
3424 nan
3425 Rick Famuyiwa
3426 Michael Rymer
3427 Rob Zombie
3428 Sharron Miller
3429 Ethan Coen
3430 Aaron Schneider
3431 Steve Miner
3432 Gina Prince-Bythewood
3433 Tom Ford
3434 Martin Scorsese
3435 Michael Corrente
3436 Gurinder Chadha
3437 Phillip Noyce
3438 Don Michael Paul
3439 Tony Maylam
3440 nan
3441 Mitch Davis
3442 nan
3443 Yash Chopra
3444 David Mamet
3445 Jay Duplass
3446 Kevin Brodie
3447 Paul Schrader
3448 George Hickenlooper
3449 Lynne Ramsay
3450 John Stephenson
3451 Tim Chambers
3452 Curtis Hanson
3453 Rodrigo García
3454 Dick Richards
3455 Jean-Marie Poiré
3456 Sofia Coppola
3457 Bob Gosse
3458 Alex Zamm
3459 Spencer Susser
3460 Richard Shepard
3461 Gus Van Sant
3462 Thaddeus O'Sullivan
3463 Peter Sollett
3464 Shari Springer Berman
3465 Aleksey German
3466 Stephen Milburn Anderson
3467 Richard E. Grant
3468 Troy Duffy
3469 David Lam
3470 Francis Ford Coppola
3471 Vladlen Barbe
3472 Richard Rich
3473 Clint Eastwood
3474 Robert C. Cooper
3475 Richard Linklater
3476 Kenny Ortega
3477 Kim Nguyen
3478 Jackie Earle Haley
3479 Max Färberböck
3480 Arie Posin
3481 Damian Nieman
3482 Mark Tonderai
3483 Denis Villeneuve
3484 Gabriele Muccino
3485 Ian Fitzgibbon
3486 José Padilha
3487 John R. Leonetti
3488 Rachel Perkins
3489 John Singleton
3490 Luis Valdez
3491 Alan Alda
3492 Brian De Palma
3493 Stephen Sommers
3494 Doug Liman
3495 Nicole Holofcener
3496 Robert Wise
3497 Louis Morneau
3498 Caroline Link
3499 Steve McQueen
3500 Matthew Vaughn
3501 Sterling Van Wagenen
3502 Zal Batmanglij
3503 Michael Mayer
3504 Hans Petter Moland
3505 Oren Moverman
3506 Ian Sharp
3507 Anton Corbijn
3508 James Cameron
3509 Wolfgang Becker
3510 Tom Hooper
3511 Dan O'Bannon
3512 nan
3513 Kevin Smith
3514 Randal Kleiser
3515 Oliver Stone
3516 Michael Moore
3517 George Roy Hill
3518 Robert Stevenson
3519 Robert Redford
3520 Jerome Robbins
3521 Harold Ramis
3522 Gary Hardwick
3523 Rick Famuyiwa
3524 Bryan Singer
3525 Stephen Hopkins
3526 Walt Becker
3527 Darren Aronofsky
3528 King Vidor
3529 Christopher Guest
3530 John Carpenter
3531 Spike Lee
3532 Fred Savage
3533 Sammo Kam-Bo Hung
3534 Christopher Guest
3535 Donald Petrie
3536 nan
3537 Peter Howitt
3538 Rusty Cundieff
3539 Kevin Macdonald
3540 Dominique Othenin-Girard
3541 Richard Linklater
3542 Jean-Jacques Mantello
3543 Ed Harris
3544 Risa Bramon Garcia
3545 Brian Klugman
3546 Matt Piedmont
3547 Raymond De Felitta
3548 John Michael McDonagh
3549 Deb Hagan
3550 Sofia Coppola
3551 Mark Herman
3552 Zach Cregger
3553 Zach Braff
3554 Mark Tarlov
3555 nan
3556 John Cameron Mitchell
3557 Sheldon Lettich
3558 Jon Knautz
3559 Billy Ray
3560 David Atkins
3561 Patrick Stettner
3562 Sam Peckinpah
3563 Jonathan Levine
3564 Michael Crichton
3565 Lynne Ramsay
3566 Sylvio Tabet
3567 Rick Bieber
3568 Claude Chabrol
3569 Shana Feste
3570 Wayne Wang
3571 Joey Lauren Adams
3572 Peter Cattaneo
3573 Fred Zinnemann
3574 S.R. Bindler
3575 Tony Kaye
3576 Greg Marcks
3577 Perry Lang
3578 Jake Goldberger
3579 Stefan Ruzowitzky
3580 Vic Sarin
3581 William Kaufman
3582 nan
3583 David Cronenberg
3584 Cédric Klapisch
3585 Kate Barker-Froyland
3586 Martin Koolhoven
3587 Charles Matthau
3588 John Frankenheimer
3589 Christopher M. Bessette
3590 Prachya Pinkaew
3591 Gary Sinyor
3592 nan
3593 Gurinder Chadha
3594 John Sayles
3595 Preston A. Whitmore II
3596 Ashish R. Mohan
3597 Jaume Balagueró
3598 Stewart Raffill
3599 George Roy Hill
3600 Hugh Hudson
3601 Darren Grant
3602 Scott Hicks
3603 Joseph Gordon-Levitt
3604 Clint Eastwood
3605 Terry Zwigoff
3606 Richard Eyre
3607 William Sachs
3608 Christophe Barratier
3609 Émile Gaudreault
3610 James Cox
3611 Spike Lee
3612 James Toback
3613 Aki Kaurismäki
3614 Gaspar Noé
3615 Hitoshi Matsumoto
3616 Rakeysh Omprakash Mehra
3617 Collin Schiffli
3618 George Ratliff
3619 David Wain
3620 Shane Meadows
3621 Morten Tyldum
3622 Jon Wright
3623 Michael McGowan
3624 Liv Ullmann
3625 Jeannot Szwarc
3626 Rohan Sippy
3627 James Wan
3628 Darren Lynn Bousman
3629 Dan Trachtenberg
3630 Jeff Tremaine
3631 David F. Sandberg
3632 Henry Joost
3633 Stiles White
3634 Chuck Russell
3635 Eugenio Derbez
3636 Henry Joost
3637 Henry Koster
3638 Blake Edwards
3639 Rachel Talalay
3640 Patty Jenkins
3641 Richard Fleischer
3642 Christopher Landon
3643 David Lynch
3644 Jean-Marc Vallée
3645 David Gelb
3646 Christopher Nolan
3647 Mike Flanagan
3648 Kevin Smith
3649 Stephen Daldry
3650 Nat Faxon
3651 George Jackson
3652 George Miller
3653 Maurice Joyce
3654 Robert Duvall
3655 Frank Perry
3656 Jesse Peretz
3657 Stephen Hopkins
3658 Ice Cube
3659 John Erick Dowdle
3660 Bille Woodruff
3661 Kasi Lemmons
3662 Richard Glatzer
3663 Michael Curtiz
3664 Bruce Malmuth
3665 Rob Hedden
3666 Joel Zwick
3667 Harmony Korine
3668 Joe Chappelle
3669 Alfonso Cuarón
3670 Edgar Wright
3671 Mickey Liddell
3672 John Sayles
3673 Dwight H. Little
3674 Fred Walton
3675 Barry Levinson
3676 Steve Carver
3677 Gonzalo López-Gallego
3678 Christine Jeffs
3679 John Erick Dowdle
3680 Don Coscarelli
3681 King Vidor
3682 Michael Tiddes
3683 Bill Duke
3684 Frank Borzage
3685 Bille Woodruff
3686 Mamoru Hosoda
3687 Brian Dannelly
3688 Denys Arcand
3689 Richard Lester
3690 J.S. Cardone
3691 Guy Hamilton
3692 Jay Levey
3693 Nicholaus Goossen
3694 Tamara Jenkins
3695 Sergio Leone
3696 Jon Favreau
3697 Duncan Jones
3698 Scott Marshall
3699 Ronan Chapalain
3700 Atom Egoyan
3701 Xavier Beauvois
3702 Randall Miller
3703 Jerry Belson
3704 Peter Jackson
3705 Michael Polish
3706 Dan Rush
3707 Jake Kasdan
3708 Brad Anderson
3709 Paul Schrader
3710 Michael Cuesta
3711 John Cameron Mitchell
3712 Fenton Bailey
3713 Jeremy Saulnier
3714 Billy Kent
3715 James Manera
3716 Wes Anderson
3717 Kevin Spacey
3718 Feroz Abbas Khan
3719 Errol Morris
3720 Dennis Hopper
3721 Eli Craig
3722 Nicholas Fackler
3723 Richard Wallace
3724 Morgan J. Freeman
3725 Matthew Hastings
3726 M. Night Shyamalan
3727 Brian De Palma
3728 Klaus Menzel
3729 nan
3730 Oren Peli
3731 Jaume Balagueró
3732 Paul Andrew Williams
3733 Stephen Herek
3734 Bob Saget
3735 Jim Amatulli
3736 nan
3737 William H. Macy
3738 Barrett Esposito
3739 Mitch Davis
3740 Eric Bross
3741 Paul Schrader
3742 Vicky Jewson
3743 Peter Hyams
3744 Marc Bennett
3745 Mike Mayhall
3746 Kevin Smith
3747 Stanton Barrett
3748 Jirí Menzel
3749 Fatih Akin
3750 Billy Bob Thornton
3751 Nick Murphy
3752 Eli Roth
3753 Michael Winterbottom
3754 Jeff Nichols
3755 Frank LaLoggia
3756 Jeremy Brock
3757 Scott Foley
3758 Tobe Hooper
3759 Sam Peckinpah
3760 Nicolas Winding Refn
3761 Christophe Ali
3762 Gabriela Tagliavini
3763 Shekar
3764 Shona Auerbach
3765 Leonard Farlinger
3766 Michel Leclerc
3767 Analeine Cal y Mayor
3768 Tom Kalin
3769 Hugh Wilson
3770 Randal Kleiser
3771 Mike Newell
3772 Amy Heckerling
3773 John Huston
3774 Spike Lee
3775 nan
3776 Lana Wachowski
3777 Darren Aronofsky
3778 Walter Lang
3779 Carlos Saura
3780 Oliver Stone
3781 Andrew Erwin
3782 Richard Kelly
3783 Beto Gómez
3784 Mike van Diem
3785 Jonas Åkerlund
3786 Todd Solondz
3787 Chan-wook Park
3788 René Féret
3789 Barry Skolnick
3790 Johnnie To
3791 Mateo Gil
3792 Lukas Moodysson
3793 Agnieszka Wojtowicz-Vosloo
3794 Kabir Sadanand
3795 Milos Forman
3796 Peter DeLuise
3797 Mel Brooks
3798 Raja Menon
3799 nan
3800 Ernie Barbarash
3801 Nick Love
3802 Jonathan Glazer
3803 Daniel Espinosa
3804 Niki Caro
3805 R. Balki
3806 Ivan Engler
3807 Kenny Ortega
3808 nan
3809 Richard Kwietniowski
3810 Timur Bekmambetov
3811 Neil Jordan
3812 Bob Clark
3813 George A. Romero
3814 George A. Romero
3815 Sofia Coppola
3816 Woody Allen
3817 Cecil B. DeMille
3818 Marc Forster
3819 Henry Hobson
3820 Mike Figgis
3821 Duane Journey
3822 Billy Wilder
3823 Rob Cohen
3824 Carol Reed
3825 Lisa Cholodenko
3826 John Carpenter
3827 John Sturges
3828 William Arntz
3829 Ed Gass-Donnelly
3830 Richard Linklater
3831 Woody Allen
3832 DJ Pooh
3833 DJ Pooh
3834 Wayne Kramer
3835 John Huston
3836 Patrick Stettner

3837 James Melkonian
3838 J.A. Bayona
3839 Michael Tiddes
3840 Roger Avary
3841 Alfred Hitchcock
3842 Bob Odenkirk
3843 Allison Anders
3844 Steven Shainberg
3845 Rick de Oliveira
3846 Oliver Stone
3847 Christopher Guest
3848 Jeff Franklin
3849 John Dahl
3850 Mike Mills
3851 Kevin Smith
3852 Dave McKean
3853 Ron Fricke
3854 Ruggero Deodato
3855 Gavin Wiesen
3856 Mora Stephens
3857 Mars Callahan
3858 Mike Figgis
3859 Leos Carax
3860 David Gordon Green
3861 Stefan Schwartz
3862 Renny Harlin
3863 Robert Lee King
3864 Kevin Allen
3865 Jorge Ramírez Suárez
3866 David Schwimmer
3867 Barry Levinson
3868 Sam Miller
3869 Anne Fontaine
3870 Dan Ireland
3871 Fernando León de Aranoa
3872 Jim Mickle
3873 nan
3874 Stephen Kay
3875 Karim Aïnouz
3876 Sam Levinson
3877 Julian Gilbey
3878 Vincenzo Natali
3879 Aleksandr Veledinskiy
3880 Peter H. Hunt
3881 Ruba Nadda
3882 Howard Hughes
3883 Edward Burns
3884 Phil Joanou
3885 Sean Byrne
3886 Chris Stokes
3887 Mark Griffiths
3888 Bruce Macdonald
3889 Fred Zinnemann
3890 Sidney Lumet
3891 Victor Fleming
3892 Richard Raymond
3893 Sam Peckinpah
3894 Alan Jacobs
3895 George Sidney
3896 Christopher Morris
3897 Andrucha Waddington
3898 Peter Stebbings
3899 Vincente Minnelli
3900 Dagur Kári
3901 Nicholas Hytner
3902 nan
3903 John Schlesinger
3904 Peter Cattaneo
3905 Jim Abrahams
3906 Kevin Carraway
3907 F. Gary Gray
3908 Albert Hughes
3909 nan
3910 Michael Gornick
3911 Sam Peckinpah
3912 Richard Brooks
3913 Fred Zinnemann
3914 Jack Smight
3915 Alfred Hitchcock
3916 Robert Eggers
3917 Michael Martin
3918 Edward Burns
3919 Bill Condon
3920 Juan José Campanella
3921 Gideon Raff
3922 Sam Raimi
3923 Louis C.K.
3924 Anthony C. Ferrante
3925 Salvador Carrasco
3926 André Øvredal
3927 Robert Cary
3928 Adam Rapp
3929 Angela Robinson
3930 Warren P. Sonoda
3931 Amanda Gusack
3932 Avi Nesher
3933 nan
3934 Charles Adelman
3935 Jay Oliva
3936 Charles Ferguson
3937 Uwe Boll
3938 Mark Young
3939 Daniel Petrie Jr.
3940 Antonio Simoncini
3941 Mel Brooks
3942 Luc Jacquet
3943 J.C. Chandor
3944 Eldar Rapaport
3945 Clark Gregg
3946 Damien Chazelle
3947 Fernando Meirelles
3948 Justin Kerrigan
3949 Nathan Frankowski
3950 Karen Moncrieff
3951 Thomas Vinterberg
3952 Bob Clark
3953 Alejandro Monteverde
3954 Mark L. Lester
3955 Jennifer Finnigan
3956 Eric Styles
3957 Laurent Cantet
3958 Roman Polanski
3959 John Ford
3960 Max Mayer
3961 Joshua Marston
3962 Mike Mills
3963 John Gulager
3964 John Landis
3965 Guy Hamilton
3966 Brandon Cronenberg
3967 Frank Capra
3968 Danny Boyle
3969 Spike Lee
3970 Tod Williams
3971 Kirk Jones
3972 Michael Moore
3973 Yimou Zhang
3974 Jack Sholder
3975 James Ivory
3976 James DeMonaco
3977 Scott Derrickson
3978 David Raynr
3979 Richard Brooks
3980 Ted Post
3981 Charles Martin Smith
3982 Kunihiko Yuyama
3983 Tom McLoughlin
3984 David Lean
3985 Patrick Read Johnson
3986 Alfred Hitchcock
3987 Billy Wilder
3988 Adam Marcus
3989 Alfred Hitchcock
3990 Michel Gondry
3991 John Maclean
3992 Michael Schultz
3993 Benny Boom
3994 Richard Brooks
3995 Stanley Kramer
3996 David Raynr
3997 nan
3998 Howard Hawks
3999 Nnegest Likké
4000 Richard Linklater
4001 Christopher Leitch
4002 Don Coscarelli
4003 Michael Schultz
4004 Patricia Cardoso
4005 nan
4006 Deepa Mehta
4007 Damien O'Donnell
4008 Peter M. Cohen
4009 Mira Nair
4010 Nicole Holofcener
4011 Mel Stuart
4012 Anthony Hickox
4013 Tom Schulman
4014 Terrence Malick
4015 Jill Sprecher
4016 Darren Stein
4017 Julian Schnabel
4018 Noah Baumbach
4019 Gavin Hood
4020 Todd Solondz
4021 George Gallo
4022 Kevin Smith
4023 Chan-wook Park
4024 David Nixon
4025 Jason Eisener
4026 Enrique Begne
4027 Matthew Bright
4028 Michael Landon Jr.
4029 Andrea Arnold
4030 Whit Stillman
4031 nan
4032 Leslye Headland
4033 nan
4034 Bobby Roth
4035 Tim Heidecker
4036 nan
4037 Marco Kreuzpaintner
4038 Kate Connor
4039 Deon Taylor
4040 Jason Alexander
4041 Xavier Gens
4042 Conor McPherson
4043 Will Canon
4044 Philip Zlotorynski
4045 Lance Kawas
4046 Francesca Gregorini
4047 Marcio Garcia
4048 David Wain
4049 Craig Moss
4050 Michael Jai White
4051 John Boorman
4052 Paolo Monico
4053 Youssef Delara
4054 Darin Scott
4055 Christian Sesma
4056 Monte Hellman
4057 Brian Caunter
4058 Chris D'Arienzo
4059 Walter Salles
4060 Frank Capra
4061 Isaac Florentine
4062 Susan Seidelman
4063 Michael Polish
4064 Heidi Ewing
4065 Alexandre Aja
4066 Leon Ford
4067 Hank Braxtan
4068 Craig Brewer
4069 Billy Wilder
4070 John Carl Buechler
4071 Victor Fleming
4072 Mel Brooks
4073 George A. Romero
4074 Rajkumar Hirani
4075 Victor Nunez
4076 Carroll Ballard
4077 Rohit Jugraj
4078 Thorbjørn Christoffersen
4079 John Ford
4080 Alex van Warmerdam
4081 Victor Fleming
4082 Mel Brooks
4083 Joseph Zito
4084 Pawel Pawlikowski
4085 James Ivory
4086 Frank Sebastiano
4087 Stacy Peralta
4088 Nacho Vigalondo
4089 Hao Ning
4090 Tony Giglio
4091 Stanley Donen
4092 Joe Cross
4093 Michael Tiddes
4094 Dinesh D'Souza
4095 Tom Hanks
4096 Tommy Lee Wallace
4097 Don Taylor
4098 Martin Ritt
4099 Leslie Small
4100 Gus Van Sant
4101 Zach Braff
4102 Richard Linklater
4103 Éric Tessier
4104 Alison Maclean
4105 Alice Wu
4106 Sarah Gavron
4107 Jake Schreier
4108 Isabel Coixet
4109 James Ponsoldt
4110 Randall Miller
4111 Larry Charles
4112 Joshua Tickell
4113 Tim Boxell
4114 Michael D. Sellers
4115 Reed Cowan
4116 James Dodson
4117 Stefan Ruzowitzky
4118 Alex Rivera
4119 James Gunn
4120 John Murlowski
4121 Benni Diez
4122 Danny Perez
4123 Spike Lee
4124 Robby Henson
4125 Mike Judge
4126 Zackary Adler
4127 Shane Meadows
4128 Dominic Burns
4129 George Sidney
4130 Carmen Marron
4131 Tim McCanlies
4132 George Sidney
4133 Mario Van Peebles
4134 Jason Stone
4135 Jerry Rees
4136 James Algar
4137 Jaco Booyens
4138 Steve Miner
4139 Danny Steinmann
4140 Michael Landon Jr.
4141 Jon Gunn
4142 Hayley Cloake
4143 Tay Garnett
4144 Shyam Madiraju
4145 Harmage Singh Kalirai
4146 Rita Merson
4147 Jon Knautz
4148 William Wyler
4149 Larry Clark
4150 Petter Næss
4151 Robert Fontaine
4152 Jaume Balagueró
4153 Patricia Cardoso
4154 Dan Perri
4155 Neil Mcenery-West
4156 Anthony O'Brien
4157 Terence Young
4158 Michael Herz
4159 nan
4160 Woody Allen
4161 David Robert Mitchell
4162 Woody Allen
4163 Robert Mulligan
4164 George Miller
4165 Chia-Liang Liu
4166 Kimberly Peirce
4167 Chris Kentis
4168 Florian Henckel von Donnersmarck
4169 Alex Kendrick
4170 Robert Rossen
4171 Jack Conway
4172 Sylvain Chomet
4173 Chris Eyre
4174 Shari Springer Berman
4175 Richard Linklater
4176 Alejandro G. Iñárritu
4177 Catherine Hardwicke
4178 Elia Kazan
4179 Debra Granik
4180 Kevin Macdonald
4181 Henry King
4182 Miranda July
4183 Charles Ferguson
4184 Max Joseph
4185 Jim Jarmusch
4186 David Ayer
4187 Jerry Jameson
4188 Steven Soderbergh
4189 Kevin Tenney
4190 nan
4191 John Cameron Mitchell
4192 Ari Folman
4193 Gary Rogers
4194 Charles Ferguson
4195 Marielle Heller
4196 nan
4197 David Sington
4198 Kelly Reichardt
4199 Fenton Bailey
4200 Bob Giraldi
4201 Jill Sprecher
4202 Huck Botko
4203 Luc Besson
4204 David Duchovny
4205 Mitchell Lichtenstein
4206 Lance Mungia
4207 Kundan Shah
4208 Michael Dowse
4209 Hue Rhodes
4210 Shane Meadows
4211 Roland Emmerich
4212 nan
4213 Jugal Hansraj
4214 Danny Provenzano
4215 Bill Muir
4216 Richard LaGravenese
4217 Noah Buschel
4218 Brian Yuzna
4219 Hunter Richards
4220 Laurie Collyer
4221 Aaron Hann
4222 James Watkins
4223 Catherine Hardwicke
4224 Phil Claydon
4225 Ralph Ziman
4226 John Simpson
4227 Colin Minihan
4228 Conor McMahon
4229 Chris Shadley
4230 Simon Napier-Bell
4231 Woody Allen
4232 Simon Yin
4233 Jeff Crook
4234 nan
4235 Orson Welles
4236 Dave Payne
4237 James Cox
4238 Jonas Åkerlund
4239 Brad Copeland
4240 Paul Bunnell
4241 Phil Morrison
4242 Harald Reinl
4243 James Cox
4244 Richard Lester
4245 Michael Moore
4246 Tanner Beard
4247 Scott Dow
4248 Derick Martini
4249 Jerry Dugan
4250 Tim Hunter
4251 Michael Polish
4252 William Kaufman
4253 Rodrigo Cortés
4254 Richard Ayoade
4255 Jehane Noujaim
4256 Pascal Arnold
4257 Remo
4258 James Marsh
4259 John Laing
4260 Jamal Hill
4261 Daniel Stamm
4262 Sam Taylor-Johnson
4263 Elia Kazan
4264 Stanley Kubrick
4265 Carlos Carrera
4266 Benh Zeitlin
4267 J. Lee Thompson
4268 Maggie Greenwald
4269 Vera Farmiga
4270 Vijay Chandar
4271 Morgan Spurlock
4272 Jonathan Wacks
4273 Khyentse Norbu
4274 Ted Post
4275 Richard Brooks
4276 Tony Krantz
4277 Mitchell Altieri
4278 W.D. Hogan
4279 Corey Grant
4280 Tom Tykwer
4281 Lucky McKee
4282 Richard Boddington
4283 David Hunt
4284 Patricia Riggen
4285 J. Lee Thompson
4286 Todd Field
4287 Steven R. Monroe
4288 Mark Illsley
4289 Pawel Pawlikowski
4290 Ritesh Batra
4291 Sally Potter
4292 Frank Capra
4293 Fred Zinnemann
4294 John Ford
4295 Brad J. Silverman
4296 Dave Meyers
4297 David M. Matthews
4298 Nadine Labaki
4299 Lluís Quílez
4300 Eytan Fox
4301 Francis Ford Coppola
4302 Romesh Sharma
4303 François Truffaut
4304 Adam Goldberg
4305 Travis Zariwny
4306 Adrienne Shelly
4307 Newt Arnold
4308 Frank Capra
4309 Larry Clark
4310 Noah Baumbach
4311 Charles Herman-Wurmfeld
4312 John Stockwell
4313 Alfred Hitchcock
4314 Atom Egoyan
4315 Vincent Gallo
4316 James Wan
4317 Alex Cox
4318 Fabián Bielinsky
4319 Dror Moreh
4320 Rebecca Miller
4321 Maggie Carey
4322 Roger Avary
4323 Henry Bean
4324 David Gordon Green
4325 Simeon Rice
4326 Brad Anderson
4327 Jeff Garlin
4328 Qasim Basir
4329 Adam Green
4330 Charles Chaplin
4331 Pete Jones
4332 Bruce Campbell
4333 Mark Brown
4334 Adam Carolla
4335 Ira Sachs
4336 John Sayles
4337 Bruce McDonald
4338 James Mottern
4339 Jaime Zevallos
4340 Rob Zombie
4341 Gerard Johnstone
4342 Robert Greenwald
4343 David Ray
4344 Dave Rodriguez
4345 Nae Caranfil
4346 David Winning
4347 Frank Lotito
4348 Timothy Woodward Jr.
4349 Tara Subkoff
4350 Russell Friedenberg
4351 William Cottrell
4352 Lucrecia Martel
4353 Edward Dmytryk
4354 Zak Penn
4355 Alex Ranarivelo
4356 Jon Knautz
4357 Mathieu Amalric
4358 David Worth
4359 Leslie H. Martinson
4360 Guy Ritchie
4361 Robert M. Young
4362 nan
4363 Thomas Vinterberg
4364 Steve Buscemi
4365 Ham Tran
4366 Rich Cowan
4367 Boris Rodriguez
4368 nan
4369 Sadyk Sher-Niyaz
4370 Paul Donovan
4371 Jonathan Kesselman
4372 Arjun Sablok
4373 Craig Moss
4374 Tyler Oliver
4375 Alfred Hitchcock
4376 Steve Miner
4377 Billy Wilder
4378 Douglas Cheek
4379 Youssef Delara
4380 Deryck Broom
4381 Henry Hathaway
4382 John Ford
4383 nan
4384 Spike Lee
4385 Steven Soderbergh
4386 James Wan
4387 Jay Chandrasekhar
4388 Giovanni Zelko
4389 Claudia Sainte-Luce
4390 Mira Nair
4391 Kenneth Lonergan
4392 Alfred Hitchcock
4393 Jamie Babbit
4394 David Boyd
4395 Quentin Tarantino
4396 Walter Lang
4397 Sergio Leone
4398 Anna Muylaert
4399 Steve Taylor
4400 Kurt Voss
4401 Léa Pool
4402 James David Pasternak
4403 Laurent Bouhnik
4404 Tom Sanchez
4405 David Caffrey
4406 Adam Jay Epstein
4407 Michael Curtiz
4408 Justin Thomas Ostensen
4409 Brenton Spencer
4410 Rob Bowman
4411 Ossie Davis
4412 Jay Alaimo
4413 Dylan Bank
4414 Rob McKittrick
4415 Shane Meadows
4416 nan
4417 Jeff Burr
4418 Harry Gantz
4419 Guy Maddin
4420 Regardt van den Bergh
4421 Panos Cosmatos
4422 Gareth Evans
4423 Matthew R. Anderson
4424 Joe Marino
4425 Michael Curtiz
4426 Joel Anderson
4427 Shimit Amin
4428 Douglas Trumbull
4429 John G. Avildsen
4430 Mona Fastvold
4431 Tony Richardson
4432 Levan Gabriadze
4433 Martin Scorsese
4434 Joe Dante
4435 Terence Young
4436 Bradley Parker
4437 Clive Barker
4438 Harold Cronk
4439 Jeff Wadlow
4440 Takao Okawara
4441 Derek Cianfrance
4442 Duncan Tucker
4443 William Brent Bell
4444 Russ Meyer
4445 Robert D. Webb
4446 Davis Guggenheim
4447 Allan Dwan
4448 Martin Scorsese
4449 Eli Roth
4450 Andrew Steggall
4451 Ben Lewin
4452 Robert Kenner
4453 Andrew Erwin
4454 Brad Anderson
4455 Craig Johnson
4456 Sean Durkin
4457 Gillian Robespierre
4458 Courtney Hunt
4459 Morgan Neville
4460 James Toback
4461 Nicole Holofcener
4462 Chris Paine
4463 Greg Berlanti
4464 Don Coscarelli
4465 Marc Levin
4466 Richard Dutcher
4467 Khalid Mohamed
4468 Trey Parker
4469 David Gordon Green
4470 Finn Taylor
4471 Karen Moncrieff
4472 José Luis Valenzuela
4473 Gia Coppola
4474 Scandar Copti
4475 Goran Dukic
4476 Mike Cahill
4477 Efram Potelle
4478 Joshua Oppenheimer
4479 Alex Gibney
4480 Paul Crowder
4481 Rohit Jagessar
4482 Griffin Dunne
4483 Anthony Powell
4484 Kief Davidson
4485 Johnny Remo
4486 Vivek Agnihotri

4487 Ti West
4488 Nick Tomnay
4489 John Hamburg
4490 Nickolas Perry
4491 Dan Zukovic
4492 Craig Mazin
4493 Becky Smith
4494 Eric Nicholas
4495 Benjamin Dickinson
4496 Hal Haberman
4497 Darren Stein
4498 A. Raven Cruz
4499 Brian Trenchard-Smith
4500 Frank Whaley
4501 Amat Escalante
4502 Wajahat Rauf
4503 Katherine Brooks
4504 David Cross
4505 Randall Rubin
4506 Robert Bennett
4507 Guy Hamilton
4508 Mary Pat Kelly
4509 Lori Petty
4510 Charlie Levi
4511 Kevin Hamedani
4512 David DeCoteau
4513 Mikel Rueda
4514 Stefan C. Schaefer
4515 Michael Taliferro
4516 David DeCoteau
4517 Katie Aselton
4518 Robert Heath
4519 D. Stevens
4520 Jeffrey St. Jules
4521 Robert Hall
4522 K. King
4523 Jonathan Meyers
4524 Ralph Nelson
4525 Blair Erickson
4526 nan
4527 Allison Burnett
4528 Richard Schenkman
4529 Sanjay Rawal
4530 Elia Kazan
4531 Kat Coiro
4532 Cristian Mungiu
4533 Brian Dorton
4534 David Slade
4535 Jamie Babbit
4536 Maryam Keshavarz
4537 Ryan Coogler
4538 Ramaa Mosley
4539 James Algar
4540 Charles Herman-Wurmfeld
4541 C. Jay Cox
4542 Mariette Monpierre
4543 Tommy Oliver
4544 Jamie Travis
4545 Lee Toland Krieger
4546 Rich Christiano
4547 Paul Andrew Williams
4548 Nick Love
4549 Natalie Bible'
4550 Asghar Farhadi
4551 Justin Molotnikov
4552 Todd Solondz
4553 Victor Nunez
4554 Peter Sollett
4555 Georg Wilhelm Pabst
4556 Daniel Davila
4557 Jorge Gaggero
4558 Rod Lurie
4559 Michael Burke
4560 Catherine Jelski
4561 Shane Dawson
4562 Tommy Wirkola
4563 Ryan Little
4564 Clark Baker
4565 George Lucas
4566 Robert Greenwald
4567 Matt Maiellaro
4568 Colin Trevorrow
4569 Leslie Small
4570 Ben Wheatley
4571 Ti West
4572 Bernardo Bertolucci
4573 Neil Burger
4574 Oliver Blackburn
4575 Jonathan Levine
4576 Christopher Hutson
4577 Fred Zinnemann
4578 Steve James
4579 David LaChapelle
4580 Joseph Kosinski
4581 Michael Cuesta
4582 Caryn Waechter
4583 Emily Dell
4584 Ryan Fleck
4585 Jennifer Wynne Farmer
4586 Christopher Scott Cherot
4587 H.M. Coakley
4588 Randy Moore
4589 Chris Atkins
4590 Bill Benenson
4591 Ryan Smith
4592 Travis Romero
4593 Anna Mastro
4594 Mark Sandrich
4595 Daniel Myrick
4596 Michael Wadleigh
4597 John Landis
4598 Jon Gunn
4599 Gene Teigland
4600 Scott Ziehl
4601 Richard Montoya
4602 Johanna Schwartz
4603 William Gazecki
4604 Lance McDaniel
4605 Thomas Lilti
4606 Michael Walker
4607 Richard Lester
4608 U. Roberto Romano
4609 Amy Holden Jones
4610 Blaz Zavrsnik
4611 Alex Kendrick
4612 Pan Nalin
4613 Joe Camp
4614 Chris Kentis
4615 Matt Walsh
4616 John 'Bud' Cardos
4617 Marilyn Agrelo
4618 Tom McCarthy
4619 Brian Baugh
4620 Patrick Creadon
4621 Barry W. Blaustein
4622 Kurt Hale
4623 Siddiq Barmak
4624 Joseph Dorman
4625 Greg Harrison
4626 Kurt Hale
4627 Michael Polish
4628 Jacob Aaron Estes
4629 Morgan J. Freeman
4630 Eric Schaeffer
4631 Neema Barnette
4632 Steve Buscemi
4633 Joe Swanberg
4634 Molly Bernstein
4635 Akira Kurosawa
4636 Marius A. Markevicius
4637 Tom DiCillo
4638 Justin Lin
4639 Quentin Dupieux
4640 C. Jay Cox
4641 Alex Smith
4642 Gareth Edwards
4643 Jonathan Parker
4644 Sol Tryon
4645 Alex Craig Mann
4646 Hao Ning
4647 Stephen Kijak
4648 Marc Forster
4649 Andrew Niccol
4650 Daston Kalili
4651 William Gazecki
4652 Ol Parker
4653 Michael Hoffman Jr.
4654 Patrick Gilles
4655 Georgia Hilton
4656 Jack Heller
4657 Fernando Baez Mella
4658 Warren Sheppard
4659 Darren Lynn Bousman
4660 Justin Paul Miller
4661 Joel Paul Reisig
4662 Catherine Gund
4663 Luke Dye
4664 Michael Herz
4665 Matty Rich
4666 Paul Greengrass
4667 Alec Asten
4668 Hans Canosa
4669 Lloyd Kaufman
4670 Matthew Watts
4671 Lloyd Bacon
4672 Joe Kenemore
4673 Whit Stillman
4674 Kay Pollak
4675 Eric England
4676 Jared Hess
4677 Jeremy Saulnier
4678 Oren Peli
4679 Stacy Peralta
4680 Terry Gilliam
4681 Richard Glatzer
4682 Sue Corcoran
4683 nan
4684 Jonathan Caouette
4685 Ray Griggs
4686 Matt Jackson
4687 Lucio Fulci
4688 nan
4689 Tom Vaughan
4690 Paul Fox
4691 Stephen Frears
4692 Ari Kirschenbaum
4693 Cassandra Nicolaou
4694 Ingmar Bergman
4695 D.W. Griffith
4696 Roger Nygard
4697 Harry Beaumont
4698 Sam Raimi
4699 Franck Khalfoun
4700 Mor Loushy
4701 Henry Alex Rubin
4702 Sam Firstenberg
4703 Doug Block
4704 nan
4705 Chad Kapper
4706 Sidney Lumet
4707 Paul Fierlinger
4708 Frank Capra
4709 Yorgos Lanthimos
4710 Lauren Lazin
4711 Gavin O'Connor
4712 Gregory Widen
4713 Cédric Klapisch
4714 Peter Hedges
4715 Niall Johnson
4716 Kelly Reichardt
4717 Kelly Reichardt
4718 Eric Mendelsohn
4719 Jean-Luc Godard
4720 Florence Ayisi
4721 Pan Nalin
4722 Michael Roemer
4723 Jesse Peretz
4724 Eddie O'Flaherty
4725 Babar Ahmed
4726 John D. Hancock
4727 Paul Bartel
4728 Bruce Dellis
4729 Pece Dingo
4730 Jerome Elston Scott
4731 Étienne Faure
4732 Herb Freed
4733 Jack Perez
4734 Craig Zobel
4735 Kevin Smith
4736 Nicole Holofcener
4737 Ken Del Conte
4738 Justin Lin
4739 Maria Maggenti
4740 Miguel Arteta
4741 Piyush Dinker Pandya
4742 Daniel Columbie
4743 Vincenzo Natali
4744 Emma-Kate Croghan
4745 Bill Plympton
4746 Greg Harrison
4747 Drake Doremus
4748 Al Franklin
4749 Allison Anders
4750 Michael Kang
4751 Paul Schrader
4752 nan
4753 Lori Silverbush
4754 Jeff Nichols
4755 Stuart Hazeldine
4756 Hilary Brougher
4757 Rachel Goldenberg
4758 Corbin Bernsen
4759 Jamin Winans
4760 Tom Seidman
4761 Jason Naumann
4762 Matt Cimber
4763 Sam Martin
4764 Andrew Hyatt
4765 Joel Paul Reisig
4766 Kristin Rizzo
4767 King Vidor
4768 Ward Roberts
4769 Zoran Lisinac
4770 Nicolas Winding Refn
4771 James O'Brien
4772 Tom Putnam
4773 Jon Shear
4774 Al Silliman Jr.
4775 Eugène Lourié
4776 George Miller
4777 Doug Liman
4778 Sergio Leone
4779 Lowell Sherman
4780 Maurizio Benazzo
4781 David G. Evans
4782 Ava DuVernay
4783 Tom Tykwer
4784 Sherman Alexie
4785 Justin Dillon
4786 Stevan Mena
4787 Adam Rifkin
4788 Eric Valette
4789 Jay Duplass
4790 Livingston Oden
4791 Chris Marker
4792 Carl Theodor Dreyer
4793 Marianna Palka
4794 Richard Schenkman
4795 Ricki Stern
4796 Nadia Tass
4797 James Kerwin
4798 C. Fraser Press
4799 Rania Attieh
4800 Sharon Greytak
4801 Majid Majidi
4802 Andrew Haigh
4803 Spike Lee
4804 Cary Bell
4805 Nicolae Constantin Tanase
4806 Mike Cahill
4807 Melvin Van Peebles
4808 Ken Roht
4809 Gary Winick
4810 John Carney
4811 Robinson Devor
4812 Michel Orion Scott
4813 Pat Holden
4814 Eric Bugbee
4815 Bill Melendez
4816 Dena Seidel
4817 Deborah Anderson
4818 Sara Newens
4819 Michael Moore
4820 Sai Varadan
4821 Zal Batmanglij
4822 Amal Al-Agroobi
4823 Andrew Berends
4824 Lynn Shelton
4825 Valentine
4826 David Hewlett
4827 Jean-Luc Godard
4828 Nate Parker
4829 Nathan Smith Jones
4830 Alex Kendrick
4831 Travis Cluff
4832 David Lynch
4833 Harry F. Millarde
4834 Robert Townsend
4835 Peter Chelsom
4836 Jamaa Fanaka
4837 Larry Blamire
4838 Stephen Langford
4839 E.L. Katz
4840 Lisanne Pajot
4841 Dan Reed
4842 John Reinhardt
4843 Patrick Ryan Sims
4844 Laslo Benedek
4845 Jason Miller
4846 Sut Jhally
4847 Darren Aronofsky
4848 Julie Davis
4849 Myles Berkowitz
4850 Brett Piper
4851 Morgan Spurlock
4852 Brandon Trost
4853 Joe Swanberg
4854 Joseph Green
4855 Wade Gasque
4856 Daniel Schechter
4857 Mike Flanagan
4858 Edward Burns
4859 Matt Johnson
4860 Bruno Barreto
4861 Lena Dunham
4862 Terron R. Parsons
4863 Daniel Mellitz
4864 Jem Cohen
4865 Andrew Leman
4866 Dave Carroll
4867 William Eubank
4868 Patrick Meaney
4869 Chad Hartigan
4870 Malcolm Goodwin
4871 David Gordon Green
4872 Kevin Jordan
4873 Kirk Loudon
4874 Travis Legge
4875 Martin Scorsese
4876 Collin Joseph Neal
4877 Bradley Rust Gray
4878 Mike Bruce
4879 Andrew Bujalski
4880 Damir Catic
4881 Ben Wheatley
4882 Kevin Smith
4883 James Bidgood
4884 Andrew Bujalski
4885 Neil LaBute
4886 Eric Eason
4887 Uwe Boll
4888 Richard Linklater
4889 Joseph Mazzella
4890 Travis Legge
4891 Alex Kendrick
4892 Marcus Nispel
4893 Brandon Landers
4894 Jay Duplass
4895 Jim Chuchu
4896 Daryl Wein
4897 Jason Trost
4898 John Waters
4899 Olivier Assayas
4900 Jafar Panahi
4901 Ivan Kavanagh
4902 Kiyoshi Kurosawa
4903 Tadeo Garcia
4904 Thomas L. Phillips
4905 Ash Baron-Cohen
4906 Shane Carruth
4907 Neill Dela Llana
4908 Robert Rodriguez
4909 Anthony Vallone
4910 Edward Burns
4911 Scott Smith
4912 nan
4913 Benjamin Roberds
4914 Daniel Hsia
4915 Jon Gunn

In [24]:
movie.loc[movie['duration']==163]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
539,Color,Steven Spielberg,298.0,163.0,14000.0,412.0,Moritz Bleibtreu,745.0,47379090.0,Drama|History|Thriller,...,824.0,English,France,R,70000000.0,2005.0,486.0,7.6,2.35,0

In [25]:
movie.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [27]:
df=movie
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [30]:
df.sort_values(['duration','color'], ascending=[1,0])

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1930,Color,NaN,12.0,7.0,NaN,3.0,John Sparkes,45.0,NaN,Animation|Comedy|Family,...,12.0,English,UK,TV-G,NaN,NaN,7.0,8.3,NaN,834
2316,Color,Jane Clark,NaN,7.0,23.0,51.0,Traci Dinwiddie,344.0,NaN,Romance|Short,...,NaN,English,USA,NaN,13000.0,2007.0,281.0,5.2,1.85,30
3997,Color,NaN,38.0,11.0,NaN,0.0,Seth Green,11.0,NaN,Animation|Comedy,...,75.0,English,USA,TV-MA,NaN,NaN,0.0,7.8,1.33,1000
4564,Color,Clark Baker,1.0,14.0,0.0,37.0,Alan Pietruszewski,134.0,NaN,Horror|Sci-Fi|Short|Thriller,...,3.0,English,USA,NaN,NaN,2012.0,93.0,6.2,NaN,14
4342,Color,Robert Greenwald,56.0,20.0,21.0,0.0,Jon Hunter,0.0,NaN,Documentary,...,70.0,English,USA,Not Rated,1500000.0,2005.0,0.0,6.8,1.85,0
749,Color,NaN,8.0,22.0,NaN,402.0,Oliver Hudson,732.0,NaN,Comedy|Romance,...,41.0,English,USA,TV-PG,NaN,NaN,607.0,7.3,1.78,0
807,Color,NaN,20.0,22.0,NaN,271.0,Soleil Moon Frye,870.0,NaN,Comedy|Family|Fantasy,...,94.0,English,USA,TV-G,3000000.0,NaN,558.0,6.6,1.33,990
824,Color,NaN,26.0,22.0,NaN,676.0,Noureen DeWulf,883.0,NaN,Comedy|Romance,...,54.0,English,USA,NaN,NaN,NaN,701.0,6.7,16.00,0
1825,Color,NaN,79.0,22.0,NaN,424.0,Kaitlin Olson,813.0,NaN,Comedy,...,151.0,English,USA,TV-MA,NaN,NaN,547.0,8.8,1.33,0
4190,Color,NaN,8.0,22.0,NaN,344.0,Amy Sedaris,459.0,NaN,Comedy,...,62.0,English,USA,TV-14,NaN,NaN,396.0,8.1,4.00,558
4688,Color,NaN,11.0,22.0,NaN,6.0,Ron Lynch,59.0,NaN,Animation|Comedy|Drama,...,82.0,English,USA,TV-PG,NaN,NaN,11.0,8.2,1.33,526
276,NaN,Christopher Barnard,NaN,22.0,0.0,NaN,NaN,5.0,NaN,Comedy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.2,NaN,0
3271,Color,NaN,47.0,23.0,NaN,265.0,James Arnold Taylor,668.0,NaN,Action|Adventure|Animation|Drama|Fantasy|Sci-Fi,...,73.0,English,USA,TV-PG,NaN,NaN,296.0,7.9,2.35,2000
3873,Color,NaN,5.0,23.0,NaN,218.0,Tiffany Thornton,254.0,NaN,Comedy|Family|Romance,...,47.0,English,USA,TV-G,NaN,NaN,248.0,6.1,1.33,325
2214,Color,NaN,6.0,24.0,NaN,NaN,NaN,0.0,NaN,Action|Adventure|Animation|Family|Fantasy,...,51.0,Japanese,Japan,NaN,NaN,NaN,NaN,7.0,NaN,124
3032,Color,NaN,3.0,24.0,NaN,44.0,Johnny Flynn,381.0,NaN,Comedy,...,18.0,English,UK,NaN,NaN,NaN,102.0,7.9,NaN,0
3592,Color,NaN,15.0,25.0,NaN,220.0,Belinda Stewart-Wilson,229.0,NaN,Comedy|Romance,...,42.0,English,UK,TV-14,NaN,NaN,223.0,8.4,16.00,0
3902,Color,NaN,55.0,25.0,NaN,395.0,Jamie Farr,443.0,NaN,Comedy|Drama|War,...,147.0,English,USA,TV-PG,NaN,NaN,421.0,8.4,4.00,0
4815,Color,Bill Melendez,43.0,25.0,36.0,27.0,Bill Melendez,39.0,NaN,Animation|Comedy|Family,...,126.0,English,USA,TV-G,150000.0,1965.0,36.0,8.4,1.33,0
473,Black and White,NaN,31.0,25.0,NaN,474.0,Agnes Moorehead,1000.0,NaN,Comedy|Family|Fantasy,...,71.0,English,USA,TV-G,NaN,NaN,960.0,7.6,4.00,0
4383,Color,NaN,19.0,27.0,NaN,201.0,Riley Keough,934.0,NaN,Drama,...,17.0,English,USA,TV-MA,NaN,NaN,691.0,7.3,NaN,632
1648,Color,NaN,52.0,28.0,NaN,576.0,Kevin Connolly,680.0,NaN,Comedy|Drama,...,145.0,English,USA,TV-MA,NaN,NaN,638.0,8.5,1.78,0
638,Color,NaN,4.0,30.0,NaN,359.0,Kaitlyn Dever,995.0,NaN,Comedy,...,87.0,English,USA,TV-PG,NaN,NaN,363.0,7.4,16.00,0
817,Color,NaN,46.0,30.0,NaN,479.0,Kristin Davis,962.0,NaN,Comedy|Romance,...,238.0,English,USA,TV-MA,NaN,NaN,722.0,7.0,1.33,0
1254,Color,NaN,3.0,30.0,NaN,12.0,Melissa Altro,51.0,NaN,Animation|Comedy|Family,...,43.0,English,Canada,TV-Y,NaN,NaN,21.0,7.4,1.33,301
1955,Color,NaN,7.0,30.0,NaN,265.0,Jennifer Hale,971.0,NaN,Action|Animation|Comedy|Family|Fantasy|Sci-Fi,...,60.0,English,USA,TV-Y7,NaN,NaN,918.0,7.2,4.00,581
2165,Color,NaN,3.0,30.0,NaN,295.0,David Mann,607.0,NaN,Comedy,...,20.0,English,USA,NaN,NaN,NaN,378.0,3.5,1.85,211
2230,Color,NaN,NaN,30.0,NaN,215.0,Mark Feuerstein,909.0,NaN,Comedy,...,6.0,English,USA,NaN,NaN,NaN,417.0,6.7,1.33,4
2313,Color,NaN,NaN,30.0,NaN,9.0,George Coulouris,310.0,NaN,Drama|Family,...,NaN,English,UK,NaN,NaN,NaN,11.0,7.2,NaN,0
3246,Color,NaN,1.0,30.0,NaN,140.0,Katherine Kelly Lang,177.0,NaN,Drama|Romance,...,54.0,English,USA,TV-14,NaN,NaN,170.0,3.5,1.78,748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3582,Color,NaN,10.0,240.0,NaN,334.0,Blake Ritson,805.0,NaN,Comedy|Drama|Romance,...,50.0,English,UK,NaN,NaN,NaN,432.0,8.2,1.78,0
2066,Black and White,Richard Attenborough,95.0,240.0,0.0,249.0,Amrish Puri,545.0,NaN,Biography|Drama|History,...,256.0,English,UK,PG,22000000.0,1982.0,429.0,8.1,2.35,12000
1150,Color,Joseph L. Mankiewicz,72.0,251.0,311.0,595.0,Richard Burton,940.0,57750000.0,Biography|Drama|History|Romance,...,192.0,English,UK,Approved,31115000.0,1963.0,726.0,7.0,2.20,0
1698,Color,Sergio Leone,111.0,251.0,0.0,642.0,Burt Young,22000.0,5300000.0,Crime|Drama,...,495.0,English,Italy,R,30000000.0,1984.0,683.0,8.4,1.85,12000
2527,Color,Peter Flinth,34.0,270.0,5.0,292.0,Michael Nyqvist,908.0,NaN,Action|Adventure|Drama|Romance|War,...,54.0,Swedish,Sweden,NaN,25000000.0,2007.0,690.0,6.6,2.35,0
1963,Color,Ron Maxwell,22.0,271.0,33.0,251.0,William Morgan Sheppard,854.0,10769960.0,Drama|History|War,...,256.0,English,USA,PG,25000000.0,1993.0,702.0,7.7,1.85,0
874,Color,Ron Maxwell,84.0,280.0,33.0,67.0,Bruce Boxleitner,789.0,12870569.0,Drama|History|War,...,497.0,English,USA,PG-13,56000000.0,2003.0,640.0,6.3,2.35,953
2687,Color,NaN,9.0,286.0,NaN,527.0,Tom Hollander,857.0,NaN,Drama|History|Thriller,...,39.0,English,USA,NaN,NaN,NaN,555.0,7.9,1.78,733
1556,Color,Francis Ford Coppola,261.0,289.0,0.0,3000.0,Marlon Brando,11000.0,78800000.0,Drama|War,...,983.0,English,USA,R,31500000.0,1979.0,10000.0,8.5,2.35,19000
2922,Color,Wolfgang Petersen,96.0,293.0,249.0,18.0,Martin Semmelrogge,362.0,11433134.0,Adventure|Drama|Thriller|War,...,426.0,German,West Germany,R,14000000.0,1981.0,21.0,8.4,1.85,11000
3254,Color,Chatrichalerm Yukol,31.0,300.0,6.0,6.0,Chatchai Plengpanich,7.0,454255.0,Action|Adventure|Drama|History|War,...,47.0,Thai,Thailand,R,400000000.0,2001.0,6.0,6.6,1.85,124
1134,Color,Michael Cimino,102.0,325.0,517.0,678.0,Sam Waterston,12000.0,1500000.0,Adventure|Drama|Western,...,189.0,English,USA,R,44000000.0,1980.0,849.0,6.8,2.35,1000
1487,Color,Taylor Hackford,12.0,330.0,138.0,672.0,Jesse Borrego,848.0,4496583.0,Crime|Drama,...,129.0,English,USA,R,35000000.0,1993.0,674.0,8.0,1.66,6000
2436,Color,NaN,108.0,334.0,NaN,30.0,Nora von Waldstätten,897.0,145118.0,Biography|Crime|Drama|Thriller,...,36.0,English,France,Not Rated,NaN,NaN,30.0,7.7,2.35,0
1694,Color,NaN,16.0,511.0,NaN,51.0,Ingvar Eggert Sigurðsson,147.0,NaN,Crime|Drama|Thriller,...,19.0,Icelandic,Iceland,NaN,NaN,NaN,63.0,8.2,16.00,0
197,Color,Matt Birch,1.0,NaN,0.0,159.0,Dave Legeno,10000.0,NaN,Action|Fantasy,...,2.0,English,UK,NaN,NaN,2011.0,570.0,7.5,NaN,40
203,Color,Matt Birch,4.0,NaN,0.0,1000.0,Toby Jones,10000.0,NaN,Fantasy,...,2.0,English,UK,NaN,NaN,2010.0,2000.0,6.4,NaN,25
1495,Color,Tony Kaye,NaN,NaN,194.0,816.0,Aisha Tyler,970.0,NaN,Crime|Drama,...,NaN,English,USA,NaN,23000000.0,2009.0,856.0,7.2,NaN,26
3536,Color,NaN,10.0,NaN,NaN,502.0,Tuppence Middleton,1000.0,NaN,Drama|History|Romance|War,...,44.0,English,UK,TV-14,NaN,NaN,888.0,8.2,16.00,11000
3744,Color,Marc Bennett,2.0,NaN,3.0,723.0,Natasha Henstridge,975.0,NaN,Comedy|Drama,...,2.0,English,USA,NaN,5000000.0,2012.0,900.0,6.7,NaN,35
3763,Color,Shekar,1.0,NaN,0.0,0.0,Diganth,5.0,NaN,Comedy|Romance,...,1.0,Kannada,India,NaN,NaN,2013.0,0.0,7.1,NaN,2
4207,Color,Kundan Shah,1.0,NaN,4.0,72.0,Bobby Deol,353.0,NaN,Action|Comedy|Romance|Thriller,...,1.0,Hindi,India,NaN,NaN,2000.0,89.0,2.8,NaN,10
4297,Color,David M. Matthews,5.0,NaN,8.0,394.0,Lamman Rucker,713.0,2592808.0,Crime|Drama|Thriller,...,15.0,English,USA,R,NaN,2010.0,607.0,3.5,2.35,588
4302,Color,Romesh Sharma,4.0,NaN,0.0,45.0,Revathy,421.0,129319.0,Romance,...,4.0,English,India,NaN,70000000.0,2005.0,96.0,5.1,NaN,9
4416,Color,NaN,2.0,NaN,NaN,206.0,John Jarratt,511.0,NaN,Drama|Horror|Thriller,...,6.0,English,Australia,NaN,NaN,NaN,457.0,7.1,2.00,954
4502,Color,Wajahat Rauf,6.0,NaN,3.0,4.0,Ayesha Omar,7.0,NaN,Comedy|Family,...,15.0,Urdu,Pakistan,NaN,1000000.0,2015.0,5.0,7.0,NaN,259
4580,Color,Joseph Kosinski,4.0,NaN,364.0,567.0,Lauren Cohan,22000.0,NaN,Action|Adventure|Fantasy|Sci-Fi,...,11.0,English,USA,NaN,NaN,2014.0,4000.0,8.1,NaN,1000
4825,Color,Valentine,NaN,NaN,0.0,NaN,Valentine,17.0,NaN,Romance,...,NaN,English,USA,PG-13,125000.0,2015.0,0.0,5.1,NaN,0
4863,Color,Daniel Mellitz,NaN,NaN,0.0,15.0,Chelse Swain,1000.0,NaN,Comedy|Drama,...,3.0,English,USA,NaN,NaN,2006.0,36.0,4.7,NaN,2
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [31]:
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [33]:
df['profit']=df['gross']-df['budget']
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,523505847.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,9404152.0

In [34]:
df=df.drop(['profit'],axis=1)

In [35]:
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [11]:
type(movie)

pandas.core.frame.DataFrame

In [12]:
movie.shape#to find the nuumber of row and columns

(4916, 28)

In [8]:
movie.head() #fetch top 5 records

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [9]:
movie.tail()#fetch bottom 5 files

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [10]:
movie.head(2) #fetch top 2 records

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [11]:
movie.tail(3)#fetch bottom 3 records

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [13]:
movie.dtypes #to find the structure of type of the data

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [14]:
movie.index

RangeIndex(start=0, stop=4916, step=1)

In [7]:
index=movie.index
index

RangeIndex(start=0, stop=4916, step=1)

In [15]:
movie.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [11]:
data=movie.values
data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [12]:
director=movie['director_name']
director

0            James Cameron
1           Gore Verbinski
2               Sam Mendes
3        Christopher Nolan
4              Doug Walker
5           Andrew Stanton
6                Sam Raimi
7             Nathan Greno
8              Joss Whedon
9              David Yates
10             Zack Snyder
11            Bryan Singer
12            Marc Forster
13          Gore Verbinski
14          Gore Verbinski
15             Zack Snyder
16          Andrew Adamson
17             Joss Whedon
18            Rob Marshall
19        Barry Sonnenfeld
20           Peter Jackson
21               Marc Webb
22            Ridley Scott
23           Peter Jackson
24             Chris Weitz
25           Peter Jackson
26           James Cameron
27           Anthony Russo
28              Peter Berg
29         Colin Trevorrow
               ...
4886            Eric Eason
4887              Uwe Boll
4888     Richard Linklater
4889       Joseph Mazzella
4890          Travis Legge
4891         Alex Kendrick
4892         Marcus Nispel
4893       Brandon Landers
4894           Jay Duplass
4895            Jim Chuchu
4896            Daryl Wein
4897           Jason Trost
4898           John Waters
4899       Olivier Assayas
4900          Jafar Panahi
4901         Ivan Kavanagh
4902      Kiyoshi Kurosawa
4903          Tadeo Garcia
4904    Thomas L. Phillips
4905       Ash Baron-Cohen
4906         Shane Carruth
4907      Neill Dela Llana
4908      Robert Rodriguez
4909       Anthony Vallone
4910          Edward Burns
4911           Scott Smith
4912                   NaN
4913      Benjamin Roberds
4914           Daniel Hsia
4915              Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [13]:
type(director)

pandas.core.series.Series

In [25]:
movie.director_name

0            James Cameron
1           Gore Verbinski
2               Sam Mendes
3        Christopher Nolan
4              Doug Walker
5           Andrew Stanton
6                Sam Raimi
7             Nathan Greno
8              Joss Whedon
9              David Yates
10             Zack Snyder
11            Bryan Singer
12            Marc Forster
13          Gore Verbinski
14          Gore Verbinski
15             Zack Snyder
16          Andrew Adamson
17             Joss Whedon
18            Rob Marshall
19        Barry Sonnenfeld
20           Peter Jackson
21               Marc Webb
22            Ridley Scott
23           Peter Jackson
24             Chris Weitz
25           Peter Jackson
26           James Cameron
27           Anthony Russo
28              Peter Berg
29         Colin Trevorrow
               ...
4886            Eric Eason
4887              Uwe Boll
4888     Richard Linklater
4889       Joseph Mazzella
4890          Travis Legge
4891         Alex Kendrick
4892         Marcus Nispel
4893       Brandon Landers
4894           Jay Duplass
4895            Jim Chuchu
4896            Daryl Wein
4897           Jason Trost
4898           John Waters
4899       Olivier Assayas
4900          Jafar Panahi
4901         Ivan Kavanagh
4902      Kiyoshi Kurosawa
4903          Tadeo Garcia
4904    Thomas L. Phillips
4905       Ash Baron-Cohen
4906         Shane Carruth
4907      Neill Dela Llana
4908      Robert Rodriguez
4909       Anthony Vallone
4910          Edward Burns
4911           Scott Smith
4912                   NaN
4913      Benjamin Roberds
4914           Daniel Hsia
4915              Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [17]:
movie.director_name.value_counts(ascending=True,sort=True)#gives the name of the director and number of the movies

Joey Lauren Adams        1
Matt Cimber              1
Tuck Tucker              1
Shane Acker              1
Alec Asten               1
Christopher Barnard      1
Jennifer Finnigan        1
Blaz Zavrsnik            1
Gerald Potterton         1
William A. Fraker        1
Dagur Kári               1
Jun Falkenstein          1
Shinji Aramaki           1
Rick Friedberg           1
Andrew Traucki           1
Stanton Barrett          1
Alex Rivera              1
Shane Carruth            1
Fina Torres              1
André Téchiné            1
Chris Buck               1
Marc Abraham             1
Nick Hurran              1
David Palmer             1
Jim Jarmusch             1
Sai Varadan              1
Douglas Trumbull         1
Sarah Gavron             1
Pascal Arnold            1
David S. Ward            1
                        ..
Stephen Frears          10
Paul W.S. Anderson      10
Wes Craven              10
John McTiernan          10
Shawn Levy              11
Sam Raimi               11
Richard Donner          11
Chris Columbus          11
Francis Ford Coppola    11
Richard Linklater       11
Rob Reiner              11
Michael Bay             12
Tony Scott              12
Brian De Palma          12
Kevin Smith             12
Robert Rodriguez        13
Ron Howard              13
Robert Zemeckis         13
Joel Schumacher         13
Barry Levinson          13
Tim Burton              14
Oliver Stone            14
Renny Harlin            15
Steven Soderbergh       15
Spike Lee               16
Ridley Scott            16
Martin Scorsese         20
Clint Eastwood          20
Woody Allen             22
Steven Spielberg        26
Name: director_name, Length: 2397, dtype: int64

In [63]:
movie.info()#find the null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
color                        4897 non-null object
director_name                4814 non-null object
num_critic_for_reviews       4867 non-null float64
duration                     4901 non-null float64
director_facebook_likes      4814 non-null float64
actor_3_facebook_likes       4893 non-null float64
actor_2_name                 4903 non-null object
actor_1_facebook_likes       4909 non-null float64
gross                        4054 non-null float64
genres                       4916 non-null object
actor_1_name                 4909 non-null object
movie_title                  4916 non-null object
num_voted_users              4916 non-null int64
cast_total_facebook_likes    4916 non-null int64
actor_3_name                 4893 non-null object
facenumber_in_poster         4903 non-null float64
plot_keywords                4764 non-null object
movie_imdb_link              4916 non-null object
num_user_for_reviews         4895 non-null float64
language                     4904 non-null object
country                      4911 non-null object
content_rating               4616 non-null object
budget                       4432 non-null float64
title_year                   4810 non-null float64
actor_2_facebook_likes       4903 non-null float64
imdb_score                   4916 non-null float64
aspect_ratio                 4590 non-null float64
movie_facebook_likes         4916 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [45]:
movie.isnull().sum()     #find the null values

color                         19
director_name                102
num_critic_for_reviews        49
duration                      15
director_facebook_likes      102
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        862
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                152
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               300
budget                       484
title_year                   106
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 326
movie_facebook_likes           0
dtype: int64

In [65]:
movie.isnull().sum().sum()#total number of null values

2654

In [66]:
movie.isnull().sum().sum()

2654

In [23]:
actor_1_fb_likes=movie.actor_1_facebook_likes

In [16]:
actor_1_fb_likes.min(),actor_1_fb_likes.max(),   #measures of central tendency and dispersion
actor_1_fb_likes.mean(),actor_1_fb_likes.median(),
actor_1_fb_likes.std(),actor_1_fb_likes.sum()

(15106.986883848309, 31881444.0)

In [69]:
movie.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [35]:
movie.iloc[0:4]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000

In [27]:
actor_1_fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [71]:
director.count() # count only with values.

4814

In [72]:
len(director) #count all including null values

4916

In [73]:
movie.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [46]:
movie.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [58]:
movie=movie.set_index('movie_title')

KeyError: 'movie_title'

In [59]:
movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
John Carter,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
Spider-Man 3,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
Tangled,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
Avengers: Age of Ultron,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
Harry Potter and the Half-Blood Prince,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
Batman v Superman: Dawn of Justice,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
Superman Returns,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
Quantum of Solace,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
Pirates of the Caribbean: Dead Man's Chest,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
The Lone Ranger,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
Man of Steel,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
The Chronicles of Narnia: Prince Caspian,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
The Avengers,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
Pirates of the Caribbean: On Stranger Tides,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
Men in Black 3,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
The Hobbit: The Battle of the Five Armies,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
The Amazing Spider-Man,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
Robin Hood,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
The Hobbit: The Desolation of Smaug,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
The Golden Compass,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
King Kong,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
Titanic,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
Captain America: Civil War,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
Battleship,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
Jurassic World,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Manito,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
Rampage,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
Slacker,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
Dutch Kills,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
Dry Spell,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
Flywheel,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
Exeter,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
The Ridges,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
The Puffy Chair,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
Stories of Our Lives,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
Breaking Upwards,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
All Superheroes Must Die,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
Pink Flamingos,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
Clean,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
The Circle,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
Tin Can Man,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
The Cure,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
On the Downlow,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
Sanctuary; Quite a Conundrum,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
Bang,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
Primer,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
Cavite,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
El Mariachi,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
The Mongol King,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
Newlyweds,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
Signed Sealed Delivered,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
A Plague So Pleasant,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Shanghai Calling,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
My Date with Drew,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [60]:
movie.loc['Avatar']

color                                                                    Color
director_name                                                    James Cameron
num_critic_for_reviews                                                     723
duration                                                                   178
director_facebook_likes                                                      0
actor_3_facebook_likes                                                     855
actor_2_name                                                  Joel David Moore
actor_1_facebook_likes                                                    1000
gross                                                              7.60506e+08
genres                                         Action|Adventure|Fantasy|Sci-Fi
actor_1_name                                                       CCH Pounder
num_voted_users                                                         886204
cast_total_facebook_likes                                                 4834
actor_3_name                                                         Wes Studi
facenumber_in_poster                                                         0
plot_keywords                           avatar|future|marine|native|paraplegic
movie_imdb_link              http://www.imdb.com/title/tt0499549/?ref_=fn_t...
num_user_for_reviews                                                      3054
language                                                               English
country                                                                    USA
content_rating                                                           PG-13
budget                                                                2.37e+08
title_year                                                                2009
actor_2_facebook_likes                                                     936
imdb_score                                                                 7.9
aspect_ratio                                                              1.78
movie_facebook_likes                                                     33000
Name: Avatar, dtype: object

In [1]:
movie.head(3)

NameError: name 'movie' is not defined

In [61]:
movie['has_seen']=0

In [62]:
movie.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0

In [63]:
movie['profit']=0 #add new column profit

In [64]:
movie['profit']=movie['gross']-movie['budget']#calculating the profit

In [65]:
movie.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,profit
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,523505847.0
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,9404152.0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,-44925825.0
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,198130642.0
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,NaN
John Carter,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000,0,-190641321.0
Spider-Man 3,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0,0,78530303.0
Tangled,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000,0,-59192738.0
Avengers: Age of Ultron,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000,0,208991599.0
Harry Potter and the Half-Blood Prince,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000,0,51956980.0

In [36]:
movie.[['director_name','score']]

SyntaxError: invalid syntax (<ipython-input-36-c3bf9b03f280>, line 1)

In [66]:
profit_index=movie.columns.get_loc('gross')  #find the index for the particulars

In [67]:
profit_index

8

In [5]:
data2={'name':['Alice','Bob','charles','David','Eric'],
      'year':[2017,2017,2017,2017,2017],
      'salary':[40000,24000,31000,20000,30000]}

In [6]:
type(data2)

dict

In [7]:
import pandas as pd
df5=pd.DataFrame(data2, index=['Acme','Acme','Bilboa','Bilboa','Bilboa'])

In [8]:
df5

           name  year  salary
Acme      Alice  2017   40000
Acme        Bob  2017   24000
Bilboa  charles  2017   31000
Bilboa    David  2017   20000
Bilboa     Eric  2017   30000

In [13]:
import pandas as pd
df_filtered=df5.query('salary>30000')
df_filtered

           name  year  salary
Acme      Alice  2017   40000
Bilboa  charles  2017   31000

In [14]:
df_filtered=df5[(df5['salary']>24000) & (df5['name']=='Alice')]

In [15]:
df_filtered

       name  year  salary
Acme  Alice  2017   40000

In [16]:
df_filtered=df5[(df5['salary']>30000)]

In [17]:
df_filtered

           name  year  salary
Acme      Alice  2017   40000
Bilboa  charles  2017   31000

In [18]:
import numpy as np

In [19]:
df10=pd.DataFrame({'a':list('aabbccddeeff'),'b': list('aaaabbbbcccc'),
                                            'c':np.random.randint(5, size=12),'d':np.random.randint(9, size=12)})

In [20]:
df10

    a  b  c  d
0   a  a  2  1
1   a  a  4  7
2   b  a  0  6
3   b  a  0  8
4   c  b  3  7
5   c  b  2  3
6   d  b  4  4
7   d  b  3  6
8   e  c  1  1
9   e  c  2  7
10  f  c  4  1
11  f  c  2  3

In [21]:
import numpy as np
t= np.random.randint(2,20)
for t in range (2,40,2):
       print(t)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38

In [22]:
id_list= ["a","b","c"]
id_list

['a', 'b', 'c']

In [23]:
df10.query('a==@id_list')

   a  b  c  d
0  a  a  2  1
1  a  a  4  7
2  b  a  0  6
3  b  a  0  8
4  c  b  3  7
5  c  b  2  3

In [24]:
data={'Platoon':['A','A','A','A','A','B','B','B','B','B','C','C','C','C','C'],'Casualties':[1,4,5,7,5,5,6,1,4,5,6,7,4,6,4]}

In [25]:
df=pd.DataFrame(data)

In [29]:
import pandas as pd
data={'Platoon':['A','A','A','A','A','B','B','B','B','B','C','C','C','C','C'],
      'Regiment':['A1','A2','A2','A4','A2','B1','B2','B2','B4','B4','C1','C2','C2','C2','C1'],
      'Casualties':[1,4,5,7,5,5,6,1,4,5,6,7,4,6,4]}
df2=pd.DataFrame(data)
df2

   Platoon Regiment  Casualties
0        A       A1           1
1        A       A2           4
2        A       A2           5
3        A       A4           7
4        A       A2           5
5        B       B1           5
6        B       B2           6
7        B       B2           1
8        B       B4           4
9        B       B4           5
10       C       C1           6
11       C       C2           7
12       C       C2           4
13       C       C2           6
14       C       C1           4

In [32]:
df2.groupby(['Platoon','Regiment'])['Casualties'].sum()

Platoon  Regiment
A        A1           1
         A2          14
         A4           7
B        B1           5
         B2           7
         B4           9
C        C1          10
         C2          17
Name: Casualties, dtype: int64

In [33]:
df2.groupby(['Platoon','Regiment'])['Casualties'].mean()

Platoon  Regiment
A        A1          1.000000
         A2          4.666667
         A4          7.000000
B        B1          5.000000
         B2          3.500000
         B4          4.500000
C        C1          5.000000
         C2          5.666667
Name: Casualties, dtype: float64

In [34]:
df2.columns=['species','tenant','value']
df2.index.name='label'
df2

      species tenant  value
label
0           A     A1      1
1           A     A2      4
2           A     A2      5
3           A     A4      7
4           A     A2      5
5           B     B1      5
6           B     B2      6
7           B     B2      1
8           B     B4      4
9           B     B4      5
10          C     C1      6
11          C     C2      7
12          C     C2      4
13          C     C2      6
14          C     C1      4

In [35]:
df1=pd.read_csv("Datapython\df1.csv")
df2=pd.read_csv("Datapython\df2.csv")
df1

   RollNo First_name Last_name    subject
0       1          A        QW      maths
1       2          S        WE    physics
2       3          D        RE  chemistry
3       4          F        RT   computer
4       5          G        GG     social
5       6          J        TY    english

In [36]:
df2

   subject_id  RollNo  Marks
0           1       1     86
1           2       2     90
2           3       3     78
3           4       4     95
4           5       5     67
5           6       6     68

In [38]:
df3=pd.merge(df1,df2,on='RollNo',how='inner')
df3

   RollNo First_name Last_name    subject  subject_id  Marks
0       1          A        QW      maths           1     86
1       2          S        WE    physics           2     90
2       3          D        RE  chemistry           3     78
3       4          F        RT   computer           4     95
4       5          G        GG     social           5     67
5       6          J        TY    english           6     68

In [39]:
df3

   RollNo First_name Last_name    subject  subject_id  Marks
0       1          A        QW      maths           1     86
1       2          S        WE    physics           2     90
2       3          D        RE  chemistry           3     78
3       4          F        RT   computer           4     95
4       5          G        GG     social           5     67
5       6          J        TY    english           6     68

In [40]:
df3=pd.read_csv("Datapython\df3.csv")

In [41]:
df4=pd.concat([df1,df3], axis=0) #row by row append

In [42]:
df4

   RollNo First_name Last_name    subject
0       1          A        QW      maths
1       2          S        WE    physics
2       3          D        RE  chemistry
3       4          F        RT   computer
4       5          G        GG     social
5       6          J        TY    english
0       7          A        QW      maths
1       8          S        WE    physics
2       9          D        RE  chemistry
3      10          F        RT   computer
4      11          G        GG     social
5      12          J        TY    english

In [43]:
df5=pd.concat([df1,df3], axis=1)#column by column append

In [44]:
df5

,RollNo,First_name,Last_name,subject,RollNo,First_name,Last_name,subject
0,1,A,QW,maths,7,A,QW,maths
1,2,S,WE,physics,8,S,WE,physics
2,3,D,RE,chemistry,9,D,RE,chemistry
3,4,F,RT,computer,10,F,RT,computer
4,5,G,GG,social,11,G,GG,social
5,6,J,TY,english,12,J,TY,english

In [45]:
df6=pd.read_csv("python\Datapython\survey.csv")

In [46]:
df6

      name   country  gender  age handness
0  charlie     india    male   34    right
1    harry  pakistan  female   56    right
2     dave   england    male   23    right
3   thomas     czech  female   34     left
4      joe   germany    male   56     left
5      zoe    sweden  female   23    right
6     adam  scotland    male   34     left
7      eve   ireland  female   28    right
8  marcela     wales  female   23     left
9   pankaj     india    male   45    right

In [48]:
pd.crosstab(df6.country,df6.handness)

handness  left  right
country
czech        1      0
england      0      1
germany      1      0
india        0      2
ireland      0      1
pakistan     0      1
scotland     1      0
sweden       0      1
wales        1      0

In [49]:
df6.groupby(['country','handness']).sum()

                   age
country  handness
czech    left       34
england  right      23
germany  left       56
india    right      79
ireland  right      28
pakistan right      56
scotland left       34
sweden   right      23
wales    left       23

In [50]:
df6.groupby(['country','handness']).sum()

                   age
country  handness
czech    left       34
england  right      23
germany  left       56
india    right      79
ireland  right      28
pakistan right      56
scotland left       34
sweden   right      23
wales    left       23

In [51]:
import numpy as np
t=np.random.randint(40, size=12)
list=[t]

In [55]:
l=for i in list in range(2,20,2):
     print(l)

SyntaxError: invalid syntax (<ipython-input-55-bf40c1801274>, line 1)